--ANALISE CUSTO UNITARIO PRODUTOS

SELECT DISTINCT
TO_CHAR(CAB.DTMOV,'YYYY') ANO,
TO_CHAR(CAB.DTMOV,'MM') MES,
TO_CHAR(CAB.DTMOV,'MM-YYYY') EXERCICIO,
ITE.CODPROD, 
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD, 
PRO.NCM, 
MAX(VLRUNIT)MAX,
MIN(VLRUNIT)MIN,
AVG(VLRUNIT)AVG,
STDDEV(VLRUNIT)SD
FROM TGFITE ITE
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
WHERE
CAB.DTMOV BETWEEN '01/01/2023' and '19/04/2023'

GROUP BY 
TO_CHAR(CAB.DTMOV,'YYYY'),
TO_CHAR(CAB.DTMOV,'MM'),
TO_CHAR(CAB.DTMOV,'MM-YYYY'),
ITE.CODPROD,
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD,
PRO.NCM
ORDER BY 1,2,GRU.DESCRGRUPOPROD