WITH PER AS(
SELECT
CASE WHEN sum(ITE.QTDNEG-ITE.QTDENTREGUE) = 0 THEN 'Performado' ELSE 'Não Performado' END status,
CASE WHEN FIN.AD_TIPOCOBRANCA IS NULL THEN 'Vazio' ELSE FIN.AD_TIPOCOBRANCA END AD_TIPOCOBRANCA,
CAB.NUNOTA,
cab.NUMNOTA,
sum(ITE.QTDNEG)QTDNEG,
sum(ITE.QTDENTREGUE)QTDENTREGUE,
sum(ITE.QTDNEG-ITE.QTDENTREGUE) QTDPENDENTE,
sum(fin.VLRDESDOB)VLRDESDOB,
SUM(((nvl(FIN.VLRDESDOB,0) + (CASE WHEN FIN.TIPMULTA = '1' THEN nvl(FIN.VLRMULTA,0) ELSE 0 END) 
	+ (CASE WHEN FIN.TIPJURO = '1' THEN nvl(FIN.VLRJURO,0) ELSE 0 END) + nvl(FIN.DESPCART,0) 
	+ nvl(FIN.VLRVENDOR,0) - nvl(FIN.VLRDESC,0) 
	- (CASE WHEN FIN.IRFRETIDO = 'S' THEN nvl(FIN.VLRIRF,0) ELSE 0 END) 
	- (CASE WHEN FIN.ISSRETIDO = 'S' THEN nvl(FIN.VLRISS,0) ELSE 0 END) 
	- (CASE WHEN FIN.INSSRETIDO = 'S' THEN nvl(FIN.VLRINSS,0) ELSE 0 END) 
	- nvl(FIN.CARTAODESC,0) 
	+ nvl((SELECT ROUND(SUM(I.VALOR * I.TIPIMP),2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN),0) 
	+ nvl(FIN.VLRMULTANEGOC,0) + nvl(FIN.VLRJURONEGOC,0) 
	- nvl(FIN.VLRMULTALIB,0) - nvl(FIN.VLRJUROLIB,0) 
	+ nvl(FIN.VLRVARCAMBIAL,0)) * nvl(FIN.RECDESP,0))*-1)*-1VLRLIQ
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
left JOIN TGFFIN FIN ON CAB.NUNOTA = FIN.NUNOTA
WHERE CAB.CODTIPOPER = 1111 AND FIN.DHBAIXA IS NULL
GROUP BY CAB.NUNOTA,cab.NUMNOTA,FIN.AD_TIPOCOBRANCA
ORDER BY 1)
SELECT 
sum(CASE WHEN per.status = 'Performado' AND per.ad_tipocobranca = 'Vazio' THEN VLRLIQ END) Performado,
sum(CASE WHEN per.status = 'Não Performado' AND per.ad_tipocobranca = 'Vazio' THEN VLRLIQ END) Nao_Performado,
sum(CASE WHEN per.status = 'Performado' AND per.ad_tipocobranca = 'Vazio' THEN VLRLIQ END) +
sum(CASE WHEN per.status = 'Não Performado' AND per.ad_tipocobranca = 'Vazio' THEN VLRLIQ END) Total
FROM PER 
WHERE  status in ('Não Performado', 'Performado') AND ad_tipocobranca = 'Vazio'
