

-- cartao quantidade produzida no mes
SELECT 
gru.DESCRGRUPOPROD,
SUM(ipa.QTDPRODUZIR) AS QTDPRODUZIR
FROM TPRIPROC roc
INNER JOIN tpripa ipa ON roc.idiproc = ipa.idiproc
INNER JOIN tgfpro pro ON ipa.codprodpa = pro.CODPROD
INNER JOIN tgfgru gru ON pro.CODGRUPOPROD = gru.CODGRUPOPROD 
WHERE roc.DHTERMINO IS NOT NULL
AND roc.DHTERMINO >= TRUNC(SYSDATE, 'MM')
AND PRO.CODGRUPOPROD IN ('2030000','2040000')
GROUP BY gru.DESCRGRUPOPROD




-- dash quantidade produzida quebrado por semana
SELECT DISTINCT
    TO_CHAR(roc.DHTERMINO, 'WW') AS SEMANA, 
    gru.DESCRGRUPOPROD,
    SUM(ipa.QTDPRODUZIR) AS QTDPRODUZIDA
FROM TPRIPROC roc
INNER JOIN tpripa ipa ON roc.idiproc = ipa.idiproc
INNER JOIN tgfpro pro ON ipa.codprodpa = pro.CODPROD
INNER JOIN tgfgru gru ON pro.CODGRUPOPROD = gru.CODGRUPOPROD 
WHERE roc.DHTERMINO IS NOT NULL
AND roc.DHTERMINO >= TRUNC(SYSDATE, 'MM')
AND PRO.CODGRUPOPROD IN ('2030000','2040000')
GROUP BY 
    TO_CHAR(roc.DHTERMINO, 'WW'),
    gru.DESCRGRUPOPROD
ORDER BY 1



--cartao referente a pedidos entregues
SELECT 
    gru.DESCRGRUPOPROD,
    SUM(ITE.QTDENTREGUE) AS QTDENTREGUE
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN tgfpro pro ON iTE.codprod = pro.CODPROD
INNER JOIN tgfgru gru ON pro.CODGRUPOPROD = gru.CODGRUPOPROD
WHERE
CAB.DTNEG >= TRUNC(SYSDATE, 'MM')
AND PRO.CODGRUPOPROD IN ('2030000','2040000')
AND CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L'
GROUP BY gru.DESCRGRUPOPROD




--dash referente a pedidos entregues no mes por semana
SELECT 
    TO_CHAR(cab.DTNEG, 'WW') AS SEMANA, 
    gru.DESCRGRUPOPROD,
    SUM(ITE.QTDENTREGUE) AS QTDENTREGUE
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN tgfpro pro ON iTE.codprod = pro.CODPROD
INNER JOIN tgfgru gru ON pro.CODGRUPOPROD = gru.CODGRUPOPROD
WHERE
CAB.DTNEG >= TRUNC(SYSDATE, 'MM')
AND PRO.CODGRUPOPROD IN ('2030000','2040000')
GROUP BY gru.DESCRGRUPOPROD,TO_CHAR(cab.DTNEG, 'WW')
ORDER BY 1



