/*
 * Consulta com notas fiscais de venda futura tgfcab top especifica
 * relancionando com tabela de docuementos relacionados tgfvar para obter
 * remessas, devolução remessa e complemento
 * 
 */

-- venda entrega futura

WITH ITE2 AS (SELECT NUNOTA,SUM(QTDNEG) AS QTDNEG1 FROM TGFITE GROUP BY NUNOTA)

SELECT DISTINCT 
CAB.NUNOTA,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.CODPARC,
CAB.DTNEG,
CAB.DTMOV,
CAB.VLRFRETE,
CAB.VLRNOTA,
ITE2.QTDNEG1,
CAB.BASEICMS, 
CAB.VLRICMS
FROM TGFCAB CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN ITE2 ON CAB.NUNOTA = ITE2.NUNOTA
WHERE 
CAB.CODTIPOPER = 1111
AND ((CAB.DTNEG >= :P_DTNEG.INI AND CAB.DTNEG <= :P_DTNEG.FIN) OR :P_DTNEG.FIN IS NULL)
AND (CAB.CODPARC = :CAB.CODPARC  OR :CAB.CODPARC IS NULL)
AND (CAB.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
ORDER BY CAB.NUNOTA

-- detalhe
SELECT DISTINCT
NUNOTA, QTDNEG, VLRUNIT, VLRTOT
FROM TGFITE
WHERE
NUNOTA = :A_NUNOTAORIG


--remessa - venda entrega futura
WITH TES AS (SELECT DISTINCT NUNOTA,SUM(QTDATENDIDA) AS QTDATENDIDA2 FROM TGFVAR GROUP BY NUNOTA)
SELECT DISTINCT
VAR.NUNOTAORIG,
VAR.NUNOTA,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.CODPARC,
CAB.DTNEG,
CAB.DTMOV,
CAB.VLRFRETE,
CASE WHEN VAR.QTDATENDIDA = 0 THEN 0 ELSE CAB.VLRNOTA END VLRNOTA,
CAB.BASEICMS, 
CAB.VLRICMS,
TES.QTDATENDIDA2
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
WHERE CAB.CODTIPOPER IN (1112)
AND VAR.NUNOTAORIG = :A_NUNOTAORIG
ORDER BY VAR.NUNOTA

--detalhe
SELECT DISTINCT
NUNOTA, QTDNEG, VLRUNIT, VLRTOT
FROM TGFITE
WHERE
NUNOTA = :A_NUNOTA1


--remessa - venda entrega futura
SELECT DISTINCT
VAR.NUNOTAORIG,
CAB.NUNOTA,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.CODPARC,
CAB.DTNEG,
CAB.DTMOV,
CAB.VLRFRETE,
CAB.VLRNOTA,
CAB.BASEICMS, 
CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
WHERE CAB.CODTIPOPER IN(1152,1132)
AND VAR.NUNOTAORIG = :A_NUNOTAORIG

--detalhe
SELECT DISTINCT
NUNOTA, QTDNEG, VLRUNIT, VLRTOT
FROM TGFITE
WHERE
NUNOTA = :A_NUNOTA2