

WITH ITE2 AS (SELECT NUNOTA,SUM(QTDNEG)QTDNEG1,SUM(VLRTOT)VLRTOT FROM TGFITE GROUP BY NUNOTA)
SELECT DISTINCT 
CAB.NUNOTA NUNOTAORIG,
1 NUNOTA1,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.DTNEG,
CAB.DTMOV,
ITE2.QTDNEG1,
ITE2.VLRTOT,
CAB.VLRNOTA,
CAB.VLRFRETE,
CAB.BASEICMS, 
CAB.VLRICMS
FROM TGFCAB CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN ITE2 ON CAB.NUNOTA = ITE2.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
CAB.CODTIPOPER = 1111 AND cab.NUNOTA =5665
--AND ((CAB.DTNEG >= :P_DTNEG.INI AND CAB.DTNEG <= :P_DTNEG.FIN) OR :P_DTNEG.FIN IS NULL)
--AND (CAB.CODPARC = :P_PARCEIRO  OR :P_PARCEIRO IS NULL)
--AND (CAB.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
--AND (CAB.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)
UNION ALL
WITH
TES AS (SELECT NUNOTA FROM TGFVAR GROUP BY NUNOTA),
ITE AS (SELECT NUNOTA,SUM(QTDNEG)QTDNEG1,SUM(VLRTOT)VLRTOT FROM TGFITE GROUP BY NUNOTA)
SELECT DISTINCT
VAR.NUNOTAORIG,
VAR.NUNOTA NUNOTA1,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.DTNEG,
CAB.DTMOV,
ite.QTDNEG1,
ite.VLRTOT,
CAB.VLRNOTA,
CAB.VLRFRETE,
CAB.BASEICMS, 
CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER IN (1112)  AND VAR.NUNOTAORIG = 5665
--ORDER BY 1,2
--AND VAR.NUNOTAORIG = :A_NUNOTA








WITH ITE2 AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
, TES AS (
    SELECT NUNOTAORIG,NUNOTA
    FROM TGFVAR
    GROUP BY NUNOTAORIG,NUNOTA
)
, ITE AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
SELECT DISTINCT 
    CAB.NUNOTA AS NUNOTAORIG,
    1 AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    ITE2.QTDNEG1,
    ITE2.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS, 
    CAB.VLRICMS
FROM TGFCAB CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN ITE2 ON CAB.NUNOTA = ITE2.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE CAB.CODTIPOPER = 1111 --AND CAB.NUNOTA = 5665
AND ((CAB.DTNEG >= :P_DTNEG.INI AND CAB.DTNEG <= :P_DTNEG1) OR :P_DTNEG2 IS NULL)
AND (CAB.CODPARC = :P_PARCEIRO  OR :P_PARCEIRO IS NULL)
AND (CAB.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
AND (CAB.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)

UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.VLRTOT*-1 ELSE 0 END VLRTOT,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRNOTA*-1 ELSE 0 END VLRNOTA,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRFRETE*-1 ELSE 0 END VLRFRETE,
    CAB.BASEICMS, 
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER = 1112 --AND VAR.NUNOTAORIG = 5665
AND ((CAB.DTNEG >= :P_DTNEG.INI AND CAB.DTNEG <= :P_DTNEG.FIN) OR :P_DTNEG.FIN IS NULL)
AND (CAB.CODPARC = :P_PARCEIRO  OR :P_PARCEIRO IS NULL)
AND (VAR.NUNOTAORIG = :P_NUNOTA OR :P_NUNOTA IS NULL)
AND (CAB.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)


UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
	CASE WHEN CAB.CODTIPOPER IN (1152,1132) THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    ITE.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS, 
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER IN (1152,1132) --AND VAR.NUNOTAORIG = 5665
AND ((CAB.DTNEG >= :P_DTNEG.INI AND CAB.DTNEG <= :P_DTNEG.FIN) OR :P_DTNEG.FIN IS NULL)
AND (CAB.CODPARC = :P_PARCEIRO  OR :P_PARCEIRO IS NULL)
AND (VAR.NUNOTAORIG = :P_NUNOTA OR :P_NUNOTA IS NULL)
AND (CAB.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)







WITH ITE2 AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
, TES AS (
    SELECT NUNOTAORIG,NUNOTA
    FROM TGFVAR
    GROUP BY NUNOTAORIG,NUNOTA
)
, ITE AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
SELECT DISTINCT
    CAB.NUNOTA AS NUNOTAORIG,
    1 AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    ITE2.QTDNEG1,
    ITE2.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFCAB CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN ITE2 ON CAB.NUNOTA = ITE2.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE CAB.CODTIPOPER = 1111

UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.VLRTOT*-1 ELSE 0 END VLRTOT,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRNOTA*-1 ELSE 0 END VLRNOTA,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRFRETE*-1 ELSE 0 END VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER = 1112

UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
	CASE WHEN CAB.CODTIPOPER IN (1152,1132) THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    ITE.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER IN (1152,1132)
AND (CAB.CODPARC = $P{P_PARCEIRO}  OR $P{P_PARCEIRO} IS NULL)
AND (VAR.NUNOTAORIG = $P{P_NUNOTA} OR $P{P_NUNOTA} IS NULL)
AND (CAB.NUMNOTA = $P{P_NUMNOTA} OR $P{P_NUMNOTA} IS NULL)



AND ((CAB.DTNEG >= $P{P_DTNEG1} AND CAB.DTNEG <= $P{P_DTNEG2}) OR ($P{P_DTNEG1} IS NULL OR $P{P_DTNEG2}IS NULL))



WITH ITE2 AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
, TES AS (
    SELECT NUNOTAORIG,NUNOTA
    FROM TGFVAR
    GROUP BY NUNOTAORIG,NUNOTA
)
, ITE AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.VLRTOT*-1 ELSE 0 END VLRTOT,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRNOTA*-1 ELSE 0 END VLRNOTA,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRFRETE*-1 ELSE 0 END VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER = 1112





WITH ITE2 AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
, TES AS (
    SELECT NUNOTAORIG,NUNOTA
    FROM TGFVAR
    GROUP BY NUNOTAORIG,NUNOTA
)
, ITE AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
SELECT DISTINCT
    CAB.NUNOTA AS NUNOTAORIG,
    1 AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    ITE2.QTDNEG1,
    ITE2.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFCAB CAB
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN ITE2 ON CAB.NUNOTA = ITE2.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE CAB.CODTIPOPER = 1111

UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.QTDNEG1 ELSE 0 END QTDNEG1,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.VLRTOT ELSE 0 END VLRTOT,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRNOTA ELSE 0 END VLRNOTA,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRFRETE ELSE 0 END VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER = 1112

UNION ALL

SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
	CASE WHEN CAB.CODTIPOPER IN (1152,1132) THEN ITE.QTDNEG1*-1 ELSE 0 END QTDNEG1,
    ITE.VLRTOT,
    CAB.VLRNOTA,
    CAB.VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER IN (1152,1132)

ORDER BY 1,2 



WITH ITE2 AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
, TES AS (
    SELECT NUNOTAORIG,NUNOTA
    FROM TGFVAR
    GROUP BY NUNOTAORIG,NUNOTA
)
, ITE AS (
    SELECT NUNOTA, SUM(QTDNEG) AS QTDNEG1, SUM(VLRTOT) AS VLRTOT
    FROM TGFITE
    GROUP BY NUNOTA
)
SELECT DISTINCT
    TES.NUNOTAORIG AS NUNOTAORIG,
    TES.NUNOTA AS NUNOTA1,
    CAB.CODTIPOPER,
    TOP.DESCROPER,
    CAB.NUMNOTA,
    CAB.CODPARC,
    PAR.RAZAOSOCIAL,
    CAB.DTNEG,
    CAB.DTMOV,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.QTDNEG1 ELSE 0 END QTDNEG1,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN ITE.VLRTOT ELSE 0 END VLRTOT,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRNOTA ELSE 0 END VLRNOTA,
    CASE WHEN CAB.CODTIPOPER = 1112 THEN CAB.VLRFRETE ELSE 0 END VLRFRETE,
    CAB.BASEICMS,
    CAB.VLRICMS
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TES ON VAR.NUNOTA = TES.NUNOTA
INNER JOIN ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE CAB.CODTIPOPER = 1112