WITH
----entre
CAB AS (
SELECT
CAB.NUNOTA,
SUM(ITE.QTDNEG)QTDNEG,
SUM(ITE.QTDENTREGUE)QTDENTREGUE,
SUM(ITE.QTDNEG-ITE.QTDENTREGUE)SALDO 
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
GROUP BY CAB.NUNOTA),
---var
VAR AS (SELECT 
NUNOTA,
NUNOTAORIG
FROM TGFVAR GROUP BY NUNOTA,NUNOTAORIG),
---MENOR DTPRVE
MEV AS (SELECT
NUNOTA,
MIN(DTPREV)MENOR_DTPREV
FROM TGFDTP
GROUP BY NUNOTA),
TOT AS (
SELECT DISTINCT 
FIN.VLRDESDOB
FROM TGFFIN FIN
INNER JOIN TGFTOP TOP ON FIN.CODTIPOPER = TOP.CODTIPOPER 
INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
INNER JOIN CAB ON FIN.NUNOTA = CAB.NUNOTA
INNER JOIN VAR ON FIN.NUNOTA = VAR.NUNOTA
INNER JOIN MEV ON VAR.NUNOTAORIG = MEV.NUNOTA
WHERE FIN.RECDESP = 1 AND FIN.CODTIPOPER  IN (1111) AND FIN.DHBAIXA IS NULL
AND MEV.MENOR_DTPREV > FIN.DTVENC
ORDER BY 1 DESC)
SELECT SUM(VLRDESDOB)TOTAL FROM TOT 




WITH
----entre
CAB AS (
SELECT
CAB.NUNOTA,
SUM(ITE.QTDNEG)QTDNEG,
SUM(ITE.QTDENTREGUE)QTDENTREGUE,
SUM(ITE.QTDNEG-ITE.QTDENTREGUE)SALDO 
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
GROUP BY CAB.NUNOTA),
---var
VAR AS (SELECT 
NUNOTA,
NUNOTAORIG
FROM TGFVAR GROUP BY NUNOTA,NUNOTAORIG),
---MENOR DTPRVE
MEV AS (SELECT
NUNOTA,
MIN(DTPREV)MENOR_DTPREV
FROM TGFDTP
GROUP BY NUNOTA)

SELECT DISTINCT 
MEV.MENOR_DTPREV,
FIN.DTVENC,
CASE WHEN (MEV.MENOR_DTPREV IS NULL)  OR (FIN.DTVENC IS NULL) THEN 0 ELSE MEV.MENOR_DTPREV - FIN.DTVENC END status,
FIN.NUNOTA,
VAR.NUNOTAORIG,
FIN.DESDOBRAMENTO,
FIN.CODTIPOPER,
TOP.DESCROPER,
FIN.CODPARC,
PAR.RAZAOSOCIAL,
FIN.VLRDESDOB
FROM TGFFIN FIN
INNER JOIN TGFTOP TOP ON FIN.CODTIPOPER = TOP.CODTIPOPER 
INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
INNER JOIN CAB ON FIN.NUNOTA = CAB.NUNOTA
INNER JOIN VAR ON FIN.NUNOTA = VAR.NUNOTA
INNER JOIN MEV ON VAR.NUNOTAORIG = MEV.NUNOTA
WHERE FIN.RECDESP = 1 AND FIN.CODTIPOPER  IN (1111) AND FIN.DHBAIXA IS NULL
ORDER BY 3 desc






---var
SELECT 
NUNOTA,
SEQUENCIA,
NUNOTAORIG,
SEQUENCIAORIG 
FROM TGFVAR
WHERE
NUNOTA = :A_NUNOTA


---DTPRVE
SELECT
NUNOTA,
SEQUECIA,
SEQPREV,
DTPREV,
QTD,
QTDENTREGUE,
QTD - QTDENTREGUE SALDO
FROM TGFDTP
WHERE
NUNOTA = :A_NUNOTA1



select fin.codparc, par.RAZAOSOCIAL ,sum(fin.vlrdesdob)vlrdesdob from tgffin fin
inner join tgfnat nat on fin.codnat = nat.codnat
INNER JOIN tgfpar par ON fin.codparc = par.codparc
where 
fin.codnat in (9010000) AND fin.codemp = 60
and fin.dhbaixa is null
GROUP BY fin.codparc, par.RAZAOSOCIAL