--PRODUTOS QUE FALTAM PRODUZIR
WITH EST AS (
SELECT EST.CODPROD,SUM(EST.ESTOQUE) ESTOQUE 
FROM TGFEST EST 
inner join tgfpro pro on EST.codprod = PRO.codprod
WHERE PRO.CODGRUPOPROD IN (2030000, 2040000)
GROUP BY EST.CODPROD)
select DISTINCT 
  ROW_NUMBER() OVER (ORDER BY DTPREV) AS ORDEM
  , cab.dtneg
  , cab.nunota
  , cab.numnota
  , ite.codprod
  , pro.descrprod
  , CASE WHEN CAB.STATUSNOTA = 'L' THEN 'Sim' ELSE 'Não' END Confirmada
  , cab.pendente StatusPendente
  , DTP.DTPREV
  , DTP.QTD AS QTDNEG
  , DTP.QTDENTREGUE
  , DTP.QTD-DTP.QTDENTREGUE as Qtd_Pendente
from tgfcab cab 
inner join tgfven ven on cab.codvend = ven.codvend
inner join tgfite ite on ite.nunota = cab.nunota
inner join tgfpar par on par.codparc = cab.codparc
inner join tgfpro pro on pro.codprod = ite.codprod
inner join tgftop top on cab.codtipoper = top.codtipoper
INNER JOIN est ON ite.codprod = est.codprod
LEFT JOIN TGFDTP DTP ON CAB.NUNOTA = DTP.NUNOTA AND ITE.SEQUENCIA = DTP.SEQUENCIA
where 
--CAB.DHTIPOPER = TOP.DHALTER
AND CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND PRO.CODGRUPOPROD IN (2030000, 2040000)
And DTPREV >= TO_DATE('01-01-2021','DD-MM-YYYY') 
AND DTPREV <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
--AND (DTP.QTD-DTP.QTDENTREGUE) <= 0
ORDER BY 2,5


----vida nova
---cabeçalho
------------------------------------------------------------------------
SELECT DISTINCT 
    cab.dtneg
  , cab.CODEMP
  , cab.CODPARC
  , par.RAZAOSOCIAL 
  , cab.nunota
  , cab.numnota
  , cab.codparc
  , CAB.PENDENTE
  , CAB.STATUSNOTA
  FROM TGFCAB CAB
  INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
  WHERE 
  CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
  --AND PRO.CODGRUPOPROD IN (2030000, 2040000)
  --And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
  --AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
  ORDER BY 3

  ---item
------------------------------------------------------------------------
WITH EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT DISTINCT 
ITE.NUNOTA,
ITE.SEQUENCIA,
ITE.CODPROD,
PRO.DESCRPROD,
ITE.QTDNEG,
ITE.QTDENTREGUE,
(ITE.QTDNEG-ITE.QTDENTREGUE)QTDPENDENTE, 
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END QTDESTOQUE,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))>0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END SALDO,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END A_PRODUZIR
FROM TGFITE ITE
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE 
ITE.NUNOTA = 4861--:A_NUNOTA--10440--18138--
ORDER BY 1

  
  
---AGRUPAMENTO ITEM
------------------------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
ANDA AS (SELECT DISTINCT IPA.CODPRODPA,IPA.QTDPRODUZIR QTDANDAMENTO FROM TGFITE ITE2
INNER JOIN TPRIPA IPA ON ITE2.CODPROD = IPA.CODPRODPA
INNER JOIN TPRIPROC ROC ON IPA.IDIPROC = ROC.IDIPROC
WHERE ROC.STATUSPROC = 'A' ORDER BY 1)
SELECT DISTINCT 
ite.codprod,
pro.DESCRPROD,
SUM(ite.QTDNEG)QTDNEG,
SUM(ITE.QTDENTREGUE)QTDENTREGUE,
SUM((ITE.QTDNEG-ITE.QTDENTREGUE))QTDPENDENTE,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) QTDESTOQUE,
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))>0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) SALDO,
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_PRODUZIR,
CASE WHEN ANDA.QTDANDAMENTO IS NULL THEN 0 ELSE ANDA.QTDANDAMENTO END QTDANDAMENTO
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
LEFT JOIN ANDA ON ITE.CODPROD = ANDA.CODPRODPA
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
--And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
--AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END),
ANDA.QTDANDAMENTO
ORDER BY 1

----TESTE
SELECT DISTINCT 
IPA.CODPRODPA,SUM(IPA.QTDPRODUZIR)QTDANDAMENTO
FROM TGFITE ITE2
INNER JOIN TPRIPA IPA ON ITE2.CODPROD = IPA.CODPRODPA
INNER JOIN TPRIPROC ROC ON IPA.IDIPROC = ROC.IDIPROC
WHERE ROC.STATUSPROC = 'A'
GROUP BY IPA.CODPRODPA ORDER BY 1



----POSICAO DE ESTOQUE POR LOTE DO ITEM SELECIONADO
-------------------------------------------------------------------------------------------
WITH EST AS (SELECT EST.CODPROD,EST.CONTROLE,EST.CODLOCAL,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD,EST.CONTROLE,EST.CODLOCAL)
SELECT DISTINCT 
ite.codprod,
pro.DESCRPROD,
EST.CONTROLE,
EST.CODLOCAL,
LOC.DESCRLOCAL,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) QTDESTOQUE
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND ITE.CODPROD =348 --:A_CODPROD3
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
ORDER BY 1



---DETALHAMENTO MATERIA PRIMA PARA PRODUZIR POR ITEM
------------------------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
ICP AS (SELECT CODPROD,VARIACAO,CODMATPRIMA,QTDMISTURA,CODVOL FROM tgficp t1 WHERE variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)),
EST1 AS (SELECT EST1.CODPROD,SUM(EST1.ESTOQUE)ESTOQUE FROM TGFEST EST1 GROUP BY EST1.CODPROD)
SELECT DISTINCT 
ICP.CODMATPRIMA,
PRO.DESCRPROD,
ICP.QTDMISTURA,
ICP.QTDMISTURA*
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) QTD_MP_NECESSARIA,
CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END QTDESTOQUE,
((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-
(ICP.QTDMISTURA*
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END)))SALDO
FROM TGFITE ITE
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN ICP ON ITE.CODPROD = ICP.CODPROD
INNER JOIN TGFPRO PRO ON ICP.CODMATPRIMA = pro.codprod
LEFT JOIN EST1 ON ICP.CODMATPRIMA = EST1.CODPROD
WHERE 
ITE.NUNOTA = 4838
AND ICP.CODPROD = 339
ORDER BY 1


---DETALHAMENTO DO PRODUTO COM AGRUPAMENTO DE MATERIA PRIMA
------------------------------------------------------------------------

WITH
ITE AS (SELECT * FROM TGFITE ITE),
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
EST1 AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
APROD AS (SELECT DISTINCT ite.codprod, pro.DESCRPROD,
(CASE
WHEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_PRODUZIR
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST1 ON ITE.CODPROD = EST1.CODPROD
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
--And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
--AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)
ORDER BY 1)
SELECT 
T1.CODMATPRIMA,
PRO3.DESCRPROD,
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END ESTOQUE,
APROD.A_PRODUZIR*T1.QTDMISTURA A_PRODUZIR,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) + (APROD.A_PRODUZIR*T1.QTDMISTURA) SALDO
FROM tgficp t1
INNER JOIN ITE ON T1.CODPROD = ITE.CODPROD
LEFT JOIN EST ON T1.CODMATPRIMA = EST.CODPROD 
INNER JOIN APROD ON T1.CODPROD = APROD.CODPROD
INNER JOIN TGFPRO PRO3 ON T1.CODMATPRIMA = PRO3.CODPROD 
WHERE T1.CODPROD = 263
AND T1.variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)
GROUP BY
T1.CODMATPRIMA,PRO3.DESCRPROD,T1.QTDMISTURA,EST.ESTOQUE,APROD.A_PRODUZIR
ORDER BY 1





WITH 
EST1 AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT DISTINCT 
ite.codprod,
pro.DESCRPROD,
(CASE
WHEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_PRODUZIR
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST1 ON ITE.CODPROD = EST1.CODPROD
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
--And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
--AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)
ORDER BY 1









SELECT CODPROD, COUNT(CODPROD) FROM TGFFCP
GROUP BY CODPROD ORDER BY 2 DESC 
------------------------------------------------------------------------

SELECT 
*
FROM TGFICP
WHERE CODPROD = 146






















-----ESTATICO POSICAO DE VARREDURA
----------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT
PRO.CODPROD,
PRO.DESCRPROD,
EST.ESTOQUE
FROM TGFPRO PRO
INNER JOIN EST ON PRO.CODPROD = EST.CODPROD
WHERE
PRO.DESCRPROD LIKE '%VARREDU%'



-----ESTATICO DE MP
----------------------------------------------------------------
---DETALHAMENTO DO PRODUTO COM AGRUPAMENTO DE MATERIA PRIMA
------------------------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
ICP AS (SELECT CODPROD,VARIACAO,CODMATPRIMA,QTDMISTURA,CODVOL FROM tgficp t1 WHERE variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)),
EST1 AS (SELECT EST1.CODPROD,SUM(EST1.ESTOQUE)ESTOQUE FROM TGFEST EST1 GROUP BY EST1.CODPROD),
EST2 AS (SELECT EST2.CODPROD,SUM(EST2.ESTOQUE)ESTOQUE FROM TGFEST EST2 GROUP BY EST2.CODPROD),
MP1 AS (SELECT DISTINCT 
ICP.CODMATPRIMA,
PRO1.DESCRPROD,
CASE WHEN ((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM((ITE.QTDNEG-ITE.QTDENTREGUE)))<= 0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM((ITE.QTDNEG-ITE.QTDENTREGUE))))*ICP.QTDMISTURA ELSE 0 END A_PRODUZIR,
PRO1.ESTMIN
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN ICP ON ITE.CODPROD = ICP.CODPROD
INNER JOIN TGFPRO PRO1 ON ICP.CODMATPRIMA = pro1.codprod
INNER JOIN EST2 ON ICP.CODMATPRIMA = EST2.CODPROD 
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
--And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
--AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ICP.CODMATPRIMA,
PRO1.DESCRPROD,
ICP.QTDMISTURA,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END),
EST2.ESTOQUE,
PRO1.ESTMIN
ORDER BY 1),
EST3 AS (SELECT EST3.CODPROD,SUM(EST3.ESTOQUE)ESTOQUE FROM TGFEST EST3 GROUP BY EST3.CODPROD),
PC_PEND AS (SELECT DISTINCT ITE.CODPROD,PRO.DESCRPROD,SUM((ITE.QTDNEG-ITE.QTDENTREGUE))QTDPEND FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.PENDENTE ='S' AND CAB.CODTIPOPER =107 GROUP BY ITE.CODPROD,PRO.DESCRPROD)
SELECT 
MP1.CODMATPRIMA,
MP1.DESCRPROD,
SUM(MP1.A_PRODUZIR)A_PRODUZIR,
EST3.ESTOQUE,
EST3.ESTOQUE+SUM(MP1.A_PRODUZIR)SALDO,
(CASE WHEN PC_PEND.QTDPEND IS NULL THEN 0 ELSE PC_PEND.QTDPEND END) PC_PENDENTE,
CASE WHEN MP1.ESTMIN IS NULL THEN 0 ELSE MP1.ESTMIN END ESTMIN
FROM MP1
INNER JOIN EST3 ON MP1.CODMATPRIMA = EST3.CODPROD
LEFT JOIN PC_PEND ON MP1.CODMATPRIMA = PC_PEND.CODPROD
GROUP BY MP1.CODMATPRIMA, MP1.DESCRPROD, EST3.ESTOQUE,PC_PEND.QTDPEND,MP1.ESTMIN
ORDER BY 1



-----MP = PEDIDO PENDENTE = SIM  E TOP 107
SELECT DISTINCT
ITE.CODPROD,PRO.DESCRPROD,SUM(ITE.QTDNEG)QTDNEG
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.PENDENTE ='S' AND CAB.CODTIPOPER =107
GROUP BY ITE.CODPROD,PRO.DESCRPROD



SELECT DISTINCT
SUM(ITE.QTDNEG)QTDNEG
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.PENDENTE ='S' AND CAB.CODTIPOPER =107







SELECT * FROM TGFICP
SELECT * FROM TPRLSP
SELECT * FROM TPRISP
SELECT CODPROD,DESCRPROD,CODGRUPOPROD,CODVOL,ESTMIN 
FROM TGFPRO WHERE CODPROD IN (408,2219,2227,263)

SELECT * FROM TGFFCP WHERE CODPROD = 2018 ORDER BY 1
SELECT * FROM TGFICP WHERE CODPROD = 2018 ORDER BY 1
SELECT * FROM TGFCAB WHERE CODTIPOPER IN ( 1000,1003,1013,1111)

--pegar a ultima versao do produto
SELECT * FROM tgficp t1 WHERE variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod) AND CODPROD =263






---VERIFICACAO DOS PRODUTOS
SELECT 
ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA,MAX(ICP.VARIACAO) VERSAO
FROM TGFICP ICP 
INNER JOIN TGFPRO PRO ON ICP.CODPROD = PRO.CODPROD
INNER JOIN TGFPRO PRO1 ON ICP.CODMATPRIMA = PRO1.CODPROD
GROUP BY ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA
ORDER BY 1


---VERIFICACAO DOS PRODUTOS - FILTRADO
SELECT 
ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA,MAX(ICP.VARIACAO) VERSAO
FROM TGFICP ICP 
INNER JOIN TGFPRO PRO ON ICP.CODPROD = PRO.CODPROD
INNER JOIN TGFPRO PRO1 ON ICP.CODMATPRIMA = PRO1.CODPROD
WHERE 
ICP.CODPROD = 2315
GROUP BY ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA
ORDER BY 1


SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TPRIPROC' AND CAM.NOMECAMPO='STATUSPROC'
ORDER BY OPC.ORDEM

