-----------Dash Transportador
SELECT 
CAB.DTNEG,CAB.CODPARC,PAR.NOMEPARC,PAR.RAZAOSOCIAL, PAR.TRANSPORTADORA,CAB.VLRNOTA
FROM TGFCAB CAB
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE
PAR.TRANSPORTADORA = 'S'
CAB.NUNOTA = 10494


SELECT * FROM TGFNCT ORDER BY 1