
---- venda futura
--MOVIMENTACAO FINANCEIRA DAS VENDAS SINTETICO
SELECT DISTINCT 
FIN.DTVENC,
FIN.NUNOTA,
FIN.DESDOBRAMENTO,
FIN.CODTIPOPER,
TOP.DESCROPER,
FIN.CODPARC,
PAR.RAZAOSOCIAL,
SUM(FIN.VLRDESDOB)VLRDESDOB
FROM TGFFIN FIN
INNER JOIN TGFTOP TOP ON FIN.CODTIPOPER = TOP.CODTIPOPER 
INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
WHERE FIN.RECDESP = 1 AND FIN.CODTIPOPER  IN (1111) AND FIN.DHBAIXA IS NULL
GROUP BY
FIN.DTVENC,
FIN.NUNOTA,
FIN.DESDOBRAMENTO,
FIN.CODTIPOPER,
TOP.DESCROPER,
FIN.CODPARC,
PAR.RAZAOSOCIAL
ORDER BY 1


----entre
SELECT
CAB.NUNOTA,
SUM(ITE.QTDNEG)QTDNEG,
SUM(ITE.QTDENTREGUE)QTDENTREGUE,
SUM(ITE.QTDNEG-ITE.QTDENTREGUE)SALDO 
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
WHERE
CAB.NUNOTA = :A_NUNOTA
GROUP BY CAB.NUNOTA

---var
SELECT 
NUNOTA,
SEQUENCIA,
NUNOTAORIG,
SEQUENCIAORIG 
FROM TGFVAR
WHERE
NUNOTA = :A_NUNOTA


---DTPRVE
SELECT
NUNOTA,
SEQUECIA,
SEQPREV,
DTPREV,
QTD,
QTDENTREGUE,
QTD - QTDENTREGUE SALDO
FROM TGFDTP
WHERE
NUNOTA = :A_NUNOTA1
