-----------Dash Transportador
SELECT 
CAB.NUNOTA,CAB.DTNEG,CAB.CODPARC,PAR.NOMEPARC,PAR.RAZAOSOCIAL,CAB.VLRNOTA,CAB.BASEICMS,CAB.VLRICMS, CAB.VLRFRETE
FROM TGFCAB CAB
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE
CAB.NUNOTA = 10494
AND(CAB.DTNEG >= TO_DATE('16-02-2023','DD-MM-YYYY') AND CAB.DTNEG <= TO_DATE('16-03-2023','DD-MM-YYYY'))


SELECT
ITE.SEQUENCIA, ITE.CODPROD, PRO.DESCRPROD,ITE.CODVOL,ITE.QTDNEG,ITE.VLRUNIT,ITE.VLRTOT
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE ITE.NUNOTA = 5528


SELECT
CAB.NUNOTA,CAB.NUMNOTA,CAB.VLRNOTA,CAB.TIPMOV 
FROM TGFVAR VAR
INNER JOIN TGFCAB CAB ON VAR.NUNOTAORIG = CAB.NUNOTA
WHERE VAR.NUNOTA = 7699

SELECT
VAR.NUNOTAORIG,ITE.NUNOTA,ITE.QTDNEG,ITE.VLRUNIT,ITE.VLRTOT
FROM TGFVAR VAR
INNER JOIN TGFITE ITE ON VAR.NUNOTAORIG = ITE.NUNOTA
WHERE VAR.NUNOTA = 7698


SELECT * FROM TGFNCT NCT
WHERE TG

SELECT
ITE.SEQUENCIA, ITE.CODPROD, PRO.DESCRPROD,ITE.CODVOL,ITE.QTDNEG,ITE.VLRUNIT,ITE.VLRTOT
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE ITE.NUNOTA = 5528

SELECT * FROM TGFVAR WHERE NUNOTA = 9736

SELECT
NCT.NUNOTA,CAB.NUMNOTA,CAB.CODPARC CODTRANSP,PAR.RAZAOSOCIAL TRANSP,NCT.SEQUENCIA,NCT.DTEMISSAO,NCT.VLRNOTA,CAB.VLRNOTA,CAB.BASEICMS,CAB.VLRICMS, CAB.VLRFRETE,NCT.CHAVENFE,NCT.NUMERO,NCT.CODPARCREM,PAR1.RAZAOSOCIAL PARCREM,NCT.CODPARCDEST,PAR2.RAZAOSOCIAL PARCDESTINO
FROM TGFNCT NCT
INNER JOIN TGFCAB CAB ON NCT.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TGFPAR PAR1 ON NCT.CODPARCREM = PAR1.CODPARC
INNER JOIN TGFPAR PAR2 ON NCT.CODPARCDEST = PAR2.CODPARC
--WHERE NCT.NUNOTA =10494
ORDER BY 1

SELECT * 
FROM TGFNCT NCT
INNER JOIN TGFCAB CAB ON NCT.NUMERO = CAB.NUMNOTA







SELECT 
PAR.CODPARC,PAR.RAZAOSOCIAL
FROM TGFPAR PAR

SELECT * FROM TGFVAR
WHERE NUNOTA =7699

12561
10494



  HAVING (MIN(dtp.dtprev) IS NULL OR MIN(dtp.dtprev) >= DATE :P_DTPREV_ATE.INI AND MIN(dtp.dtprev) <= DATE :P_DTPREV_ATE.FIN)