SELECT * FROM tcbcdm
SELECT * FROM tcbtdm
SELECT * FROM tcbdmt
sELECT * FROM tcblan
SELECT * FROM TCBPLA



SELECT
    LAN.CODEMP,
    LAN.CODCTACTB,
    CDM.CODDMT,
    DMT.DESCRDMT,
    DMT.CODTDM,
    TDM.DESCRICAO,
    PLA.CTACTB,
    PLA.DESCRCTA,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 1 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M01,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 2 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M02,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 3 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M03,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 4 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M04,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 5 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M05,    
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 6 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M06,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 7 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M07,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 8 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M08,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 9 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M09,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 10 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M10,
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 11 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M11,    
    SUM(CASE WHEN EXTRACT(MONTH FROM LAN.REFERENCIA) = 12 AND EXTRACT(YEAR FROM LAN.REFERENCIA) = EXTRACT(YEAR FROM SYSDATE) THEN LAN.VLRLANC ELSE 0 END) AS M12    
FROM
    TCBLAN LAN
    INNER JOIN TCBCDM CDM ON LAN.CODCTACTB = CDM.CODCTACTB
    INNER JOIN TCBDMT DMT ON CDM.CODDMT = DMT.CODDMT
    INNER JOIN TCBTDM TDM ON DMT.CODTDM = TDM.CODTDM
    INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE 
	DMT.CODTDM = 2
GROUP BY     
    LAN.CODEMP,
    LAN.CODCTACTB,
    CDM.CODDMT,
    DMT.DESCRDMT,
    DMT.CODTDM,
    TDM.DESCRICAO,
    PLA.CTACTB,
    PLA.DESCRCTA
ORDER BY PLA.CTACTB