SELECT DISTINCT
SUM(ITE.VLRTOT) VLRTOT
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
AND CAB.CODNAT IN(3050100)
AND (CAB.DTMOV >= TO_DATE('01-03-2023','DD-MM-YYYY')
AND CAB.DTMOV <= TO_DATE('21-08-2023','DD-MM-YYYY'))
ORDER BY CAB.DTMOV


SELECT DISTINCT
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
SUM(ITE.VLRTOT) VLRTOT
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE
CAB.CODVEICULO <> 0
AND CAB.CODNAT IN(3050100)
AND (CAB.DTMOV >= TO_DATE('01-03-2023','DD-MM-YYYY')
AND CAB.DTMOV <= TO_DATE('21-08-2023','DD-MM-YYYY'))
GROUP BY
VEI.CODBEM,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA
ORDER BY 2