SELECT * FROM TSILIB WHERE NUCHAVE = 5487


P_COMPRADOR
SELECT * FROM TSILIB
SELECT * FROM TGFCAB
SELECT * FROM TGFCOT


SELECT * FROM TSILIB


---filtro de EMPRESA
WITH
USU2 AS (SELECT CODUSU,NOMEUSU FROM TSIUSU)
SELECT DISTINCT 
CAB.CODEMP AS VALUE,
CAB.CODEMP|| ' - ' ||EMP.RAZAOSOCIAL AS LABEL
FROM tsilib lib
INNER JOIN tgfcab cab ON lib.nuchave = cab.nunota
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP 
WHERE cab.TIPMOV = 'O'
GROUP BY
CAB.CODEMP,
EMP.RAZAOSOCIAL
ORDER BY 1







--prazo geral e quantidade
SELECT DISTINCT 
COUNT(LIB.DHLIB - LIB.DHSOLICIT) QTD,
MAX(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_MAX,
MIN(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_MIN,
AVG(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_AVG,
STDDEV(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_STD
FROM tsilib lib
INNER JOIN tgfcab cab ON lib.nuchave = cab.nunota
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP 
WHERE cab.TIPMOV = 'O'
AND CAB.CODEMP IN :P_CODEMP
AND ((LIB.DHSOLICIT >= :P_PERIODO.INI AND LIB.DHSOLICIT <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
ORDER BY 1




--prazo por grupo de produTo
SELECT DISTINCT 
PRO.DESCRPROD 
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
COUNT(LIB.DHLIB - LIB.DHSOLICIT) QTD,
MAX(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_MAX,
MIN(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_MIN,
AVG(LIB.DHLIB - LIB.DHSOLICIT) PRAZO_AVG
FROM tsilib lib
INNER JOIN tgfcab cab ON lib.nuchave = cab.nunota
INNER JOIN TGFITE ITE ON LIB.nuchave = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP 
WHERE cab.TIPMOV = 'O'
AND CAB.CODEMP IN :P_CODEMP
AND ((LIB.DHSOLICIT >= :P_PERIODO.INI AND LIB.DHSOLICIT <= :P_PERIODO.FIN)
  OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
GROUP BY
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD
ORDER BY 1






--DOCUMENTOS LIBERADOS
WITH
USU2 AS (SELECT CODUSU,NOMEUSU FROM TSIUSU)
SELECT DISTINCT 
CAB.NUNOTA,
CAB.TIPMOV,
CAB.CODUSUINC,
USU2.NOMEUSU,
SUM(LIB.DHLIB - LIB.DHSOLICIT) PRAZO,
CAB.CODPARC, 
PAR.RAZAOSOCIAL,
CAB.VLRNOTA,
LIB.VLRLIBERADO 
FROM tsilib lib
INNER JOIN tgfcab cab ON lib.nuchave = cab.nunota
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP 
WHERE cab.TIPMOV = 'O'
AND CAB.CODEMP IN :P_CODEMP
AND ((LIB.DHSOLICIT >= :P_PERIODO.INI AND LIB.DHSOLICIT <= :P_PERIODO.FIN)
  OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
GROUP BY
CAB.NUNOTA,
CAB.TIPMOV,
CAB.CODUSUINC,USU2.NOMEUSU,
CAB.CODPARC, 
PAR.RAZAOSOCIAL,
CAB.VLRNOTA,
LIB.VLRLIBERADO
ORDER BY 1

WITH
ITE AS (
SELECT PRO.CODGRUPOPROD 
FROM TGFITE ITE 
INNER JOIN TGFPRO PRO ON ITE.CODPROD =PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
GROUP BY PRO.CODGRUPOPROD
)
SELECT DISTINCT
--CAB.NUNOTA,CAB.CODEMP,CAB.CODPARC,PAR.RAZAOSOCIAL,CAB.VLRNOTA
COUNT(CAB.NUNOTA)a
FROM TGFCAB CAB
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN ITE ON ITE.CODGRUPOPROD
WHERE 
CAB.STATUSNOTA = 'L'
AND CAB.PENDENTE ='N'
AND CAB.TIPMOV ='O'


SELECT CODUSU,NOMEUSU FROM tsiusu WHERE CODUSU IN (0,5,6,45,8,12,4)

STP_GET_CODUSULOGADO IN (0,5,6,45,8,12,4)



SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFCAB' AND CAM.NOMECAMPO='TIPMOV'
ORDER BY OPC.ORDEM