SELECT * FROM tgfcot
SELECT * FROM tgfmopc
SELECT * FROM tgfitc ITC

SELECT * FROM tgfcce 
SELECT 
CAB.NUMCOTACAO,
CAB.NUNOTA,
CAB.TIPMOV,
CAB.VLRNOTA 
FROM TGFCAB CAB
WHERE
(CAB.NUMCOTACAO IS NOT NULL)
AND CAB.TIPMOV = 'O'

SELECT 
    AVG(ITC.DTCOLETAPRECO - ITC.DTENVIOCOT)PRAZO
FROM tgfitc ITC
INNER JOIN TGFPAR PAR ON ITC.CODPARC = PAR.CODPARC
INNER JOIN TGFPRO PRO ON ITC.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE
    (ITC.DTENVIOCOT IS NOT NULL AND ITC.DTCOLETAPRECO IS NOT NULL)


SELECT 
    AVG(ITC.DTCOLETAPRECO - ITC.DTENVIOCOT )PRAZO,
    GRU.DESCRGRUPOPROD
FROM tgfitc ITC
INNER JOIN TGFPAR PAR ON ITC.CODPARC = PAR.CODPARC
INNER JOIN TGFPRO PRO ON ITC.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE
    (:apply_filter = 0 OR (ITC.DTENVIOCOT IS NOT NULL AND ITC.DTCOLETAPRECO IS NOT NULL))
GROUP BY GRU.DESCRGRUPOPROD




SELECT 
    ITC.NUMCOTACAO,
    ITC.DTENVIOCOT,
    ITC.DTCOLETAPRECO,
    ITC.DTCOLETAPRECO - ITC.DTENVIOCOT PRAZO,
    ITC.TIPOCOLPRECO,
    ITC.CODPARC,
    PAR.RAZAOSOCIAL,
    ITC.CODPROD,
    PRO.DESCRPROD,
    GRU.DESCRGRUPOPROD
    FROM tgfitc ITC
INNER JOIN TGFPAR PAR ON ITC.CODPARC = PAR.CODPARC
INNER JOIN TGFPRO PRO ON ITC.CODPROD = PRO.CODPROD 
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE
    (:apply_filter = 0 OR (ITC.DTENVIOCOT IS NOT NULL AND ITC.DTCOLETAPRECO IS NOT NULL));


   
   
