--filtro empresa
SELECT 
CAB.CODEMP AS VALUE, CAB.CODEMP||' - '||EMP.RAZAOSOCIAL AS LABEL
FROM tgfcab cab
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP 
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
GROUP BY
CAB.CODEMP,
EMP.RAZAOSOCIAL
ORDER BY 1 DESC

SELECT 
'TESTE' AS A
FROM TGFCAB


--filtro comprador
SELECT 
(CASE WHEN CAB.CODUSUINC IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC ELSE 9999 END) AS VALUE,
(CASE WHEN CAB.CODUSUINC IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC ||' - '||USU.NOMEUSU ELSE '9999 - OUTROS'  END) AS LABEL
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
GROUP BY 
(CASE WHEN CAB.CODUSUINC IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC ELSE 9999 END),
(CASE WHEN CAB.CODUSUINC IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC ||' - '||USU.NOMEUSU ELSE '9999 - OUTROS'  END)
ORDER BY 1





--CARTAO TOTAL DE COMPRAS
SELECT 
SUM(CAB.VLRNOTA)VLRNOTA,
COUNT(CAB.CODUSUINC)COMPRAS,
COUNT(CASE WHEN CAB.CODUSUINC IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC END) EQUIPE,
COUNT(CASE WHEN CAB.CODUSUINC NOT IN (0,5,6,9,45,85,8,12,4,80) THEN CAB.CODUSUINC END) OUTROS
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND EXTRACT(MONTH FROM CAB.DTNEG) = EXTRACT(MONTH FROM SYSDATE)
AND EXTRACT(YEAR FROM CAB.DTNEG) = EXTRACT(YEAR FROM SYSDATE)
AND CAB.CODEMP =60

--TOTAL DE COMPRAS POR PERIODO
SELECT 
TO_CHAR(CAB.DTNEG,'MM')MES,
TO_CHAR(CAB.DTNEG,'YYYY')ANO,
TO_CHAR(CAB.DTNEG,'MM-YYYY')MES_ANO,
COUNT(CAB.VLRNOTA)QTD,
SUM(CAB.VLRNOTA)VLRNOTA
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND CAB.CODEMP IN :P_CODEMP
AND (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND CAB.CODUSUINC IN :P_COMPRADOR
AND ((cab.dtneg >= :P_PERIODO.INI AND cab.dtneg <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
GROUP BY
TO_CHAR(CAB.DTNEG,'MM'),
TO_CHAR(CAB.DTNEG,'YYYY'),
TO_CHAR(CAB.DTNEG,'MM-YYYY')
ORDER BY 2,1


--TOTAL DE COMPRAS POR FORNECEDOR 
SELECT 
CAB.CODPARC,
PAR.RAZAOSOCIAL,
COUNT(CAB.VLRNOTA)QTD,
SUM(CAB.VLRNOTA)VLRNOTA
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND CAB.CODEMP IN :P_CODEMP
AND (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND CAB.CODUSUINC IN :P_COMPRADOR
AND ((cab.dtneg >= :P_PERIODO.INI AND cab.dtneg <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
GROUP BY
CAB.CODPARC,
PAR.RAZAOSOCIAL
ORDER BY 4 DESC




--ANALITICO DE COMPRAS
SELECT DISTINCT
CAB.NUNOTA,
CAB.PENDENTE,
CAB.NUMNOTA,
CAB.DTNEG,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.VLRNOTA,
CAB.CODUSUCOMPRADOR,CAB.CODUSUINC,USU.NOMEUSU,CAB.CODVEND,USU1.NOMEUSU,
CASE WHEN CAB.CODUSUINC NOT IN (0,5,6,9,45,85,8,12,4,80) THEN 'OUTROS' ELSE 'COMPRAS'END AS VERIF
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND CAB.CODEMP IN :P_CODEMP
AND (CAB.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
AND CAB.CODUSUINC IN :P_COMPRADOR
AND ((cab.dtneg >= :P_PERIODO.INI AND cab.dtneg <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
ORDER BY CAB.DTNEG



IN (0,5,6,9,45,85,8,12,4,80)



SELECT 
CAB.NUNOTA,
CAB.PENDENTE,
CAB.NUMNOTA,
CAB.DTNEG,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.VLRNOTA,
CAB.CODUSUCOMPRADOR,CAB.CODUSUINC,USU.NOMEUSU,CAB.CODVEND,USU1.NOMEUSU,
CASE WHEN CAB.CODUSUINC NOT IN (0,5,6,9,45,85,8,12,4,80) THEN '0' ELSE 'COMPRAS'END AS VERIF
FROM tgfcab cab
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIUSU USU1 ON CAB.CODVEND = USU1.CODUSU
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE 
cab.TIPMOV = 'O'
AND CAB.STATUSNOTA = 'L'
AND CAB.CODEMP =60
ORDER BY CAB.DTNEG