WITH NOM AS (
SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFPRO' AND CAM.NOMECAMPO='USOPROD'
ORDER BY OPC.ORDEM)
SELECT PRO.USOPROD VALUE, PRO.USOPROD ||' - '||NOM.OPCAO LABEL
FROM tgfpro PRO
INNER JOIN NOM ON PRO.USOPROD = NOM.VALOR

SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFPRO' AND CAM.NOMECAMPO='USOPROD'
ORDER BY OPC.ORDEM




WITH T AS (
    SELECT
        ROWNUM,CODEMP,CODPROD,DTATUAL,CUSSEMICM
    FROM (
        SELECT
            ROWNUM,CODEMP,CODPROD, DTATUAL,CUSSEMICM,
            ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
        FROM TGFCUS
    )
    WHERE rn = 1)
SELECT
    ITE.CODPROD,
    PRO.DESCRPROD,
    PRO.CODGRUPOPROD,
    GRU.DESCRGRUPOPROD,
    SUM(ITE.QTDNEG * ITE.ATUALESTOQUE) AS ESTOQUE,
    T.CUSSEMICM,
    (SUM(ITE.QTDNEG * ITE.ATUALESTOQUE)*T.CUSSEMICM) CUSSEMICM_TTL
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN T ON ITE.CODPROD = T.CODPROD
WHERE
    ITE.ATUALESTOQUE <> 0
    AND TPO.ATUALEST IN ('B', 'E', 'N')
    AND CAB.DTENTSAI <= TO_DATE('2023-09-21', 'YYYY-MM-DD')
GROUP BY
    ITE.CODPROD,
    PRO.DESCRPROD,
    PRO.CODGRUPOPROD,
    GRU.DESCRGRUPOPROD,
    T.CUSSEMICM
ORDER BY 1;




WITH CUS AS (
  SELECT 
    ROWNUM,
  	CODEMP,
    CODPROD,
    CONTROLE,
    DTATUAL,
    CUSSEMICM,
    ROW_NUMBER() OVER (PARTITION BY CODPROD, CONTROLE ORDER BY DTATUAL DESC) AS rn
  FROM TGFCUS
)
SELECT ROWNUM,CODEMP, CODPROD, CONTROLE, DTATUAL, CUSSEMICM
FROM CUS
WHERE rn = 1;




SELECT * FROM TGFCUS WHERE CODPROD = 19 AND CONTROLE = '101122022' ORDER BY 3



----multilist grupo

SELECT
PRO.CODGRUPOPROD VALUE,
PRO.CODGRUPOPROD ||' - '|| GRU.DESCRGRUPOPROD LABEL
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE 
ITE.ATUALESTOQUE <> 0  AND ATUALEST IN ('B','E','N')
GROUP BY PRO.CODGRUPOPROD,GRU.DESCRGRUPOPROD
ORDER BY GRU.DESCRGRUPOPROD



----multilist empresa
SELECT
CAB.CODEMP VALUE,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL LABEL
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
WHERE 
ITE.ATUALESTOQUE <> 0  AND TPO.ATUALEST IN ('B','E','N')
GROUP BY CAB.CODEMP,EMP.RAZAOSOCIAL
ORDER BY CAB.CODEMP

--15:29 simone

----multilist usoprod

WITH NOM AS (
SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFPRO' AND CAM.NOMECAMPO='USOPROD'
ORDER BY OPC.ORDEM)
SELECT
PRO.USOPROD VALUE, PRO.USOPROD ||' - '||NOM.OPCAO LABEL
FROM TGFITE ITE
INNER JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFTOP TPO ON CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
INNER JOIN NOM ON PRO.USOPROD = NOM.VALOR
WHERE 
ITE.ATUALESTOQUE <> 0  AND ATUALEST IN ('B','E','N')
GROUP BY PRO.USOPROD,NOM.OPCAO
ORDER BY 1