SELECT COT.CODUSUREQ,USU.NOMEUSU FROM TGFCOT COT INNER JOIN TSIUSU USU ON COT.CODUSUREQ = USU.CODUSU 
SELECT * FROM TGFCOT
SELECT *  FROM TGFCAB

WITH USU AS (SELECT CODUSU,NOMEUSU FROM TSIUSU)
SELECT DISTINCT 
	CAB.NUNOTA,
	CAB.NUMNOTA,
	CAB.DTNEG,
	CAB.CODEMP,
	EMP.RAZAOSOCIAL,
	CAB.CODPARC,
	PAR.NOMEPARC,
	CAB.NUMCOTACAO,
	COT.CODUSUREQ,
	USU.NOMEUSU,
(SELECT MAX(DHLIB) FROM TSILIB WHERE NUCHAVE = CAB.NUNOTA AND TABELA = 'TGFCAB') AS DHLIB,
CASE WHEN CAB.STATUSNOTA = 'L' THEN 'GREEN' ELSE 'RED' END AS FGCOLOR,
TPO.AD_DASHSOLCOM,
CAB.DHTIPOPER,
TPO.DHALTER,
CAB.CODTIPOPER,
TPO.CODTIPOPER
FROM TGFCAB CAB 
INNER JOIN TGFITE ITE ON ITE.NUNOTA = CAB.NUNOTA
INNER JOIN TGFPRO PRO ON PRO.CODPROD = ITE.CODPROD
INNER JOIN TGFGRU GRU ON GRU.CODGRUPOPROD = PRO.CODGRUPOPROD
INNER JOIN TGFPAR PAR ON PAR.CODPARC = CAB.CODPARC 
INNER JOIN TSIEMP EMP ON EMP.CODEMP = CAB.CODEMP
INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
INNER JOIN TGFTOP TPO ON (CAB.CODTIPOPER = TPO.CODTIPOPER AND CAB.DHTIPOPER = TPO.DHALTER)
LEFT JOIN TGFCOT COT ON CAB.NUMCOTACAO = COT.NUMCOTACAO
LEFT JOIN USU ON COT.CODUSUREQ = USU.CODUSU
WHERE 
TPO.AD_DASHSOLCOM = 'S' 
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L'
/*	AND TRUNC(CAB.DTNEG) >= :PERIODO.INI 
   AND TRUNC(CAB.DTNEG) <= :PERIODO.FIN
	AND CAB.CODEMP IN :EMPRESA
	AND GRU.CODGRUPOPROD = :A_GRUPO
	AND (CAB.CODVEND = (SELECT USU.CODVEND FROM TSIUSU USU WHERE USU.CODUSU = STP_GET_CODUSULOGADO) OR STP_GET_CODUSULOGADO IN (0,5,6,45,8,12,4))
*/
AND (CAB.NUMCOTACAO NOT IN (SELECT NUMCOTACAO FROM TGFITC WHERE NUNOTACPA IS NOT NULL) OR CAB.NUMCOTACAO IS NULL)
ORDER BY CAB.NUNOTA 
 
SELECT CODTIPOPER, AD_DASHSOLCOM FROM tgftop WHERE AD_DASHSOLCOM IS NOT null

AND (CAB.CODVEND = (SELECT USU.CODVEND FROM TSIUSU USU WHERE USU.CODUSU = STP_GET_CODUSULOGADO) OR STP_GET_CODUSULOGADO IN (0,5,6,45,8,12,4))


SELECT nunota,PENDENTE ,DHTIPOPER FROM tgfcab-- WHERE nunota =23332
SELECT * FROM TSIUSU WHERE CODUSU IN (0,5,6,9,45,85,8,12,4,80)

SELECT USU.CODVEND FROM TSIUSU USU WHERE USU.CODUSU = STP_GET_CODUSULOGADO
SELECT * FROM TSIUSU