--PRODUTOS QUE FALTAM PRODUZIR
------------------------------------------------------------------------
WITH
DTPREV AS (select DISTINCT CAB.NUNOTA, CAB.DTNEG,
case when min(dtp.dtprev) is null then cab.dtneg else min(dtp.dtprev) end dtprev
from tgfDTP DTP
LEFT JOIN TGFCAB CAB ON DTP.NUNOTA = CAB.NUNOTA
GROUP BY CAB.NUNOTA, CAB.DTNEG ORDER BY 3)
SELECT DISTINCT 
    cab.nunota
  , cab.numnota
  , cab.dtneg
  , cab.CODEMP
  , cab.CODPARC
  , par.RAZAOSOCIAL 
  , cab.codparc
  , cab.VLRNOTA
  , sum(ite.qtdneg)Qtdneg
  , sum(ite.qtdentregue)Qtdentregue
  , (sum(ite.qtdneg) - sum(ite.qtdentregue))QtdPendente
  FROM TGFCAB CAB
  INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
  inner join tgfite ite on cab.nunota = ite.nunota
  inner join tgfpro pro on ite.codprod = pro.codprod
  inner join tgfgru gru on pro.codgrupoprod = gru.codgrupoprod

  WHERE 
  CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
  AND CAB.PENDENTE = 'S'
  AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
  AND (PRO.CODGRUPOPROD IN :P_CODGRUPOPROD )
  group by
    cab.nunota
  , cab.numnota
  , cab.dtneg
  , cab.CODEMP
  , cab.CODPARC
  , par.RAZAOSOCIAL 
  , cab.codparc
  , CAB.PENDENTE
  , CAB.STATUSNOTA
  , cab.VLRNOTA
  ORDER BY 1
  
  


------------------
---Detalhe do item
------------------------------------------------------------------------
WITH EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT DISTINCT 
ITE.NUNOTA,
ITE.SEQUENCIA,
ITE.CODPROD,
PRO.DESCRPROD,
ITE.QTDNEG,
ITE.QTDENTREGUE,
(ITE.QTDNEG-ITE.QTDENTREGUE)QTDPENDENTE, 
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END QTDESTOQUE,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))>0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END SALDO,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END A_PRODUZIR
FROM TGFITE ITE
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE 
ITE.NUNOTA = :A_NUNOTA
ORDER BY 1

  ---item
------------------------------------------------------------------------
WITH EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT DISTINCT 
ITE.NUNOTA,
ITE.SEQUENCIA,
ITE.CODPROD,
PRO.DESCRPROD,
ITE.QTDNEG,
ITE.QTDENTREGUE,
(ITE.QTDNEG-ITE.QTDENTREGUE)QTDPENDENTE, 
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END QTDESTOQUE,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))>0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END SALDO,
CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END A_PRODUZIR
FROM TGFITE ITE
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE 
ITE.NUNOTA = 4861--:A_NUNOTA--10440--18138--
ORDER BY 1

  
  
---AGRUPAMENTO ITEM
------------------------------------------------------------------------
WITH
DTPREV AS (select DISTINCT CAB.NUNOTA, CAB.DTNEG,
case when min(dtp.dtprev) is null then cab.dtneg else min(dtp.dtprev) end dtprev
from tgfDTP DTP
LEFT JOIN TGFCAB CAB ON DTP.NUNOTA = CAB.NUNOTA
GROUP BY CAB.NUNOTA, CAB.DTNEG ORDER BY 3),
EST AS (SELECT DISTINCT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
ANDA AS (
Select IPA.codprodpa,sum(IPA.qtdproduzir)op_andamento from TPRIPROC roc 
LEFT join TPRIPA IPA on roc.idiproc = ipa.idiproc where statusproc = 'A' group by IPA.codprodpa ORDER BY 1)
SELECT DISTINCT 
ITE.CODPROD,
PRO.DESCRPROD,
SUM(ITE.QTDNEG)QTDNEG,
SUM(ITE.QTDENTREGUE)QTDENTREGUE,
SUM(ITE.QTDNEG-ITE.QTDENTREGUE)QTDPENDENTE,
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END ESTOQUE,
(CASE WHEN (CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE) > 0 THEN (CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE) ELSE 0 END) SALDO,
(CASE WHEN (CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE) <= 0 THEN (CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE) ELSE 0 END) A_PRODUZIR,
CASE WHEN ANDA.op_andamento IS NULL THEN 0 ELSE ANDA.op_andamento END OP_ANDAMENTO
FROM TGFITE ITE
LEFT JOIN TGFCAB CAB ON ITE.NUNOTA = CAB.NUNOTA
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
inner join tgfgru gru on pro.codgrupoprod = gru.codgrupoprod
LEFT JOIN ANDA ON ITE.CODPROD = ANDA.CODPRODPA

WHERE
CAB.CODTIPOPER IN (1000,1003,1013,1111,1005)
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
AND (PRO.CODGRUPOPROD IN :P_CODGRUPOPROD )

GROUP BY
ITE.CODPROD,
PRO.DESCRPROD,
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END,
ANDA.op_andamento
HAVING SUM(ITE.QTDNEG-ITE.QTDENTREGUE)>0
ORDER BY 1



----POSICAO DE ESTOQUE POR LOTE DO ITEM SELECIONADO
-------------------------------------------------------------------------------------------
WITH EST AS (SELECT EST.CODPROD,EST.CONTROLE,EST.CODLOCAL,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD,EST.CONTROLE,EST.CODLOCAL)
SELECT DISTINCT 
ite.codprod,
pro.DESCRPROD,
EST.CONTROLE,
EST.CODLOCAL,
LOC.DESCRLOCAL,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) QTDESTOQUE
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN TGFLOC LOC ON EST.CODLOCAL = LOC.CODLOCAL
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND ITE.CODPROD = :A_CODPROD3
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
ORDER BY 1


---DETALHAMENTO MATERIA PRIMA PARA PRODUZIR POR ITEM
------------------------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
ICP AS (SELECT CODPROD,VARIACAO,CODMATPRIMA,QTDMISTURA,CODVOL FROM tgficp t1 WHERE variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)),
EST1 AS (SELECT EST1.CODPROD,SUM(EST1.ESTOQUE)ESTOQUE FROM TGFEST EST1 GROUP BY EST1.CODPROD)
SELECT DISTINCT 
ICP.CODMATPRIMA,
PRO.DESCRPROD,
ICP.QTDMISTURA,
ICP.QTDMISTURA*
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) QTD_MP_NECESSARIA,
CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END QTDESTOQUE,
((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-
(ICP.QTDMISTURA*
(CASE
WHEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END)-(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END)))SALDO
FROM TGFITE ITE
LEFT JOIN EST ON ITE.CODPROD = EST.CODPROD
INNER JOIN ICP ON ITE.CODPROD = ICP.CODPROD
INNER JOIN TGFPRO PRO ON ICP.CODMATPRIMA = pro.codprod
LEFT JOIN EST1 ON ICP.CODMATPRIMA = EST1.CODPROD
WHERE 
ITE.NUNOTA = :A_NUNOTA --4861
AND ICP.CODPROD = :A_CODPROD -- 410
ORDER BY 1



---DETALHAMENTO DO PRODUTO COM AGRUPAMENTO DE MATERIA PRIMA
------------------------------------------------------------------------
WITH
ITE AS (SELECT * FROM TGFITE ITE),
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
EST1 AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
APROD AS (SELECT DISTINCT ite.codprod, pro.DESCRPROD,
(CASE
WHEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_NECESSARIA
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST1 ON ITE.CODPROD = EST1.CODPROD
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)
ORDER BY 1)
SELECT 
T1.CODMATPRIMA,
PRO3.DESCRPROD,
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END ESTOQUE,
APROD.A_NECESSARIA*T1.QTDMISTURA A_NECESSARIA,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) + (APROD.A_NECESSARIA*T1.QTDMISTURA) SALDO
FROM tgficp t1
INNER JOIN ITE ON T1.CODPROD = ITE.CODPROD
LEFT JOIN EST ON T1.CODMATPRIMA = EST.CODPROD 
INNER JOIN APROD ON T1.CODPROD = APROD.CODPROD
INNER JOIN TGFPRO PRO3 ON T1.CODMATPRIMA = PRO3.CODPROD 
WHERE T1.CODPROD = :A_CODPROD1 --263
AND T1.variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)
GROUP BY
T1.CODMATPRIMA,PRO3.DESCRPROD,T1.QTDMISTURA,EST.ESTOQUE,APROD.A_NECESSARIA
ORDER BY 1





-----ESTATICO POSICAO DE VARREDURA
----------------------------------------------------------
WITH 
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD)
SELECT
PRO.CODPROD,
PRO.DESCRPROD,
EST.ESTOQUE
FROM TGFPRO PRO
INNER JOIN EST ON PRO.CODPROD = EST.CODPROD
WHERE
PRO.DESCRPROD LIKE '%VARREDU%'



-----ESTATICO DE MP
----------------------------------------------------------------
---DETALHAMENTO DO PRODUTO COM AGRUPAMENTO DE MATERIA PRIMA
------------------------------------------------------------------------
WITH
PC_ANDA AS (SELECT DISTINCT ITE.CODPROD,PRO.DESCRPROD,SUM((ITE.QTDNEG-ITE.QTDENTREGUE))QTD_PC_ANDA FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.PENDENTE ='S' AND CAB.CODTIPOPER =107 GROUP BY ITE.CODPROD,PRO.DESCRPROD),
ITE AS (SELECT * FROM TGFITE ITE),
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
EST1 AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
APROD AS (SELECT DISTINCT ite.codprod, pro.DESCRPROD,
(CASE
WHEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_NECESSARIA
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
inner join tgfgru gru on pro.codgrupoprod = gru.codgrupoprod
LEFT JOIN EST1 ON ITE.CODPROD = EST1.CODPROD
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
AND (PRO.CODGRUPOPROD IN :P_CODGRUPOPROD )
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)
ORDER BY 1),
ICP AS (select codprod,codmatprima,qtdmistura,VARIACAO from tgficp icp WHERE ICP.variacao = (SELECT MAX(ICP2.variacao) FROM tgficp ICP2 WHERE ICP.codprod = ICP2.codprod)),
PRO3 AS (SELECT * FROM TGFPRO)
SELECT 
icp.codmatprima,PRO3.DESCRPROD,SUM(icp.qtdmistura*APROD.A_NECESSARIA) A_NECESSARIA1, 
case when EST.ESTOQUE is null then 0 else EST.ESTOQUE end estoque,
case when (SUM(icp.qtdmistura*APROD.A_NECESSARIA) + EST.ESTOQUE) > 0 then (SUM(icp.qtdmistura*APROD.A_NECESSARIA) + EST.ESTOQUE) else 0 end saldo,
case when (SUM(icp.qtdmistura*APROD.A_NECESSARIA) + EST.ESTOQUE) <= 0 then (SUM(icp.qtdmistura*APROD.A_NECESSARIA) + EST.ESTOQUE) else 0 end falta,
case when PC_ANDA.QTD_PC_ANDA is null then 0 else PC_ANDA.QTD_PC_ANDA end QTD_PC_ANDA
FROM ICP
INNER JOIN APROD ON ICP.CODPROD = APROD.codprod
LEFT JOIN EST ON ICP.codmatprima = EST.CODPROD
left join PC_ANDA on ICP.codmatprima = PC_ANDA.CODPROD
inner join PRO3 ON ICP.codmatprima = PRO3.CODPROD
GROUP BY
icp.codmatprima,PRO3.DESCRPROD,EST.ESTOQUE,PC_ANDA.QTD_PC_ANDA
ORDER BY 1






-----MP = PEDIDO PENDENTE = SIM  E TOP 107
SELECT DISTINCT
ITE.CODPROD,PRO.DESCRPROD,SUM(ITE.QTDNEG)QTDNEG
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
WHERE CAB.PENDENTE ='S' AND CAB.CODTIPOPER =107
GROUP BY ITE.CODPROD,PRO.DESCRPROD


--pegar a ultima versao do produto
SELECT * FROM tgficp t1 WHERE variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod) AND CODPROD =263


---VERIFICACAO DOS PRODUTOS
SELECT 
ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA,MAX(ICP.VARIACAO) VERSAO
FROM TGFICP ICP 
INNER JOIN TGFPRO PRO ON ICP.CODPROD = PRO.CODPROD
INNER JOIN TGFPRO PRO1 ON ICP.CODMATPRIMA = PRO1.CODPROD
GROUP BY ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA
ORDER BY 1


---VERIFICACAO DOS PRODUTOS - FILTRADO
SELECT 
ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA,MAX(ICP.VARIACAO) VERSAO
FROM TGFICP ICP 
INNER JOIN TGFPRO PRO ON ICP.CODPROD = PRO.CODPROD
INNER JOIN TGFPRO PRO1 ON ICP.CODMATPRIMA = PRO1.CODPROD
WHERE 
ICP.CODPROD = 2315
GROUP BY ICP.CODPROD,PRO.DESCRPROD,ICP.CODMATPRIMA,PRO1.DESCRPROD,ICP.QTDMISTURA
ORDER BY 1


SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TPRIPROC' AND CAM.NOMECAMPO='STATUSPROC'
ORDER BY OPC.ORDEM