



-----RESUMO TITULOS
WITH 
PEN AS (
    SELECT 
        CAB.NUNOTA,
        SUM(ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
        SUM(ITE.QTDENTREGUE) AS QTDENTREGUE,
        SUM(ITE.QTDNEG) AS QTDNEG,
        SUM(CASE WHEN ITE.QTDNEG IS NULL THEN 0 ELSE ITE.QTDENTREGUE / ITE.QTDNEG END) AS PERC_QTDENTREGUE,
        SUM(CASE WHEN ITE.QTDNEG IS NULL THEN 0 ELSE (ITE.QTDNEG-ITE.QTDENTREGUE) / ITE.QTDNEG END) AS PERC_QTDPENDENTE
    FROM TGFCAB CAB
    INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA 
    WHERE
        CAB.codemp = 60
        AND CAB.CODTIPOPER IN (1000, 1003, 1013, 1111, 1005)
        AND CAB.PENDENTE = 'S'
        AND CAB.STATUSNOTA = 'L'
    GROUP BY CAB.NUNOTA
)
SELECT DISTINCT
    CASE WHEN FIN.AD_TIPOCOBRANCA IS NULL THEN 'Vazio' ELSE FIN.AD_TIPOCOBRANCA END AS AD_TIPOCOBRANCA,
    SUM(CASE WHEN PEN.QTDNEG IS NULL THEN 0 ELSE PEN.QTDNEG END) AS QTDNEG,
    SUM(CASE WHEN PEN.QTDPENDENTE IS NULL THEN 0 ELSE PEN.QTDPENDENTE END) AS QTDPENDENTE,
    SUM(CASE WHEN PEN.QTDENTREGUE IS NULL THEN 0 ELSE PEN.QTDENTREGUE END) AS QTDENTREGUE,
     -- Calculate PER_ENTREGUE by multiplying PER_QTDENTREGUE by some value
    CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END *100 AS PER_QTDENTREGUE,
    CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDNEG-PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END *100 AS PER_QTDPENDENTE,
    SUM(
        (
            (
                NVL(FIN.VLRDESDOB, 0) 
                + (CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA, 0) ELSE 0 END) 
                + (CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO, 0) ELSE 0 END) 
                + NVL(FIN.DESPCART, 0) 
                + NVL(FIN.VLRVENDOR, 0) 
                - NVL(FIN.VLRDESC, 0) 
                - (CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF, 0) ELSE 0 END) 
                - (CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS, 0) ELSE 0 END) 
                - (CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS, 0) ELSE 0 END) 
                - NVL(FIN.CARTAODESC, 0) 
                + NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP), 2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN), 0) 
                + NVL(FIN.VLRMULTANEGOC, 0) 
                + NVL(FIN.VLRJURONEGOC, 0) 
                - NVL(FIN.VLRMULTALIB, 0) 
                - NVL(FIN.VLRJUROLIB, 0) 
                + NVL(FIN.VLRVARCAMBIAL, 0)
            ) * NVL(FIN.RECDESP, 0)
        ) ) AS VLRLIQ,
---

    SUM(
        (
            (
                NVL(FIN.VLRDESDOB, 0) 
                + (CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA, 0) ELSE 0 END) 
                + (CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO, 0) ELSE 0 END) 
                + NVL(FIN.DESPCART, 0) 
                + NVL(FIN.VLRVENDOR, 0) 
                - NVL(FIN.VLRDESC, 0) 
                - (CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF, 0) ELSE 0 END) 
                - (CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS, 0) ELSE 0 END) 
                - (CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS, 0) ELSE 0 END) 
                - NVL(FIN.CARTAODESC, 0) 
                + NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP), 2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN), 0) 
                + NVL(FIN.VLRMULTANEGOC, 0) 
                + NVL(FIN.VLRJURONEGOC, 0) 
                - NVL(FIN.VLRMULTALIB, 0) 
                - NVL(FIN.VLRJUROLIB, 0) 
                + NVL(FIN.VLRVARCAMBIAL, 0)
            ) * NVL(FIN.RECDESP, 0)
        ) )  *     CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END VLRLIQ_ENTREGUE,

-------
    SUM(
        (
            (
                NVL(FIN.VLRDESDOB, 0) 
                + (CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA, 0) ELSE 0 END) 
                + (CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO, 0) ELSE 0 END) 
                + NVL(FIN.DESPCART, 0) 
                + NVL(FIN.VLRVENDOR, 0) 
                - NVL(FIN.VLRDESC, 0) 
                - (CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF, 0) ELSE 0 END) 
                - (CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS, 0) ELSE 0 END) 
                - (CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS, 0) ELSE 0 END) 
                - NVL(FIN.CARTAODESC, 0) 
                + NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP), 2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN), 0) 
                + NVL(FIN.VLRMULTANEGOC, 0) 
                + NVL(FIN.VLRJURONEGOC, 0) 
                - NVL(FIN.VLRMULTALIB, 0) 
                - NVL(FIN.VLRJUROLIB, 0) 
                + NVL(FIN.VLRVARCAMBIAL, 0)
            ) * NVL(FIN.RECDESP, 0)
        ) )  *         CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDNEG-PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END VLRLIQ_PENDENTE
        FROM tgffin FIN
LEFT JOIN PEN ON FIN.NUNOTA = PEN.NUNOTA
WHERE FIN.CODTIPOPER IN (1000, 1003, 1013, 1111, 1005) AND FIN.DHBAIXA IS NULL
AND ((FIN.DTVENC >= :P_DTVENC.INI AND FIN.DTVENC <= :P_DTVENC.FIN) OR (:P_DTVENC.INI IS NULL AND :P_DTVENC.FIN IS NULL))
AND (FIN.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
AND (FIN.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)
GROUP BY FIN.AD_TIPOCOBRANCA




-----DETALHAMENTO TITULOS
WITH 
PEN AS (
    SELECT 
        CAB.NUNOTA,
        SUM(ITE.QTDNEG - ITE.QTDENTREGUE) AS QTDPENDENTE,
        SUM(ITE.QTDENTREGUE) AS QTDENTREGUE,
        SUM(ITE.QTDNEG) AS QTDNEG,
        SUM(CASE WHEN ITE.QTDNEG IS NULL THEN 0 ELSE ITE.QTDENTREGUE / ITE.QTDNEG END) AS PERC_QTDENTREGUE,
        SUM(CASE WHEN ITE.QTDNEG IS NULL THEN 0 ELSE (ITE.QTDNEG-ITE.QTDENTREGUE) / ITE.QTDNEG END) AS PERC_QTDPENDENTE
    FROM TGFCAB CAB
    INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA 
    WHERE
        CAB.codemp = 60
        AND CAB.CODTIPOPER IN (1000, 1003, 1013, 1111, 1005)
        AND CAB.PENDENTE = 'S'
        AND CAB.STATUSNOTA = 'L'
    GROUP BY CAB.NUNOTA
)
SELECT DISTINCT
	CASE WHEN FIN.AD_TIPOCOBRANCA IS NULL THEN 'Vazio' ELSE FIN.AD_TIPOCOBRANCA END AS AD_TIPOCOBRANCA,
    FIN.NUNOTA,
    FIN.NUMNOTA,
	 FIN.CODPARC,
	PAR.RAZAOSOCIAL,
	fin.codvend,
	ven.apelido,
    SUM(CASE WHEN PEN.QTDNEG IS NULL THEN 0 ELSE PEN.QTDNEG END) AS QTDNEG,
    SUM(CASE WHEN PEN.QTDPENDENTE IS NULL THEN 0 ELSE PEN.QTDPENDENTE END) AS QTDPENDENTE,
    SUM(CASE WHEN PEN.QTDENTREGUE IS NULL THEN 0 ELSE PEN.QTDENTREGUE END) AS QTDENTREGUE,
     -- Calculate PER_ENTREGUE by multiplying PER_QTDENTREGUE by some value
    (CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END)*100 AS PER_QTDENTREGUE,
    (CASE WHEN SUM(PEN.QTDNEG) IS NULL THEN 0 ELSE SUM(PEN.QTDNEG-PEN.QTDENTREGUE) / SUM(PEN.QTDNEG) END)*100 AS PER_QTDPENDENTE
FROM tgffin FIN
LEFT JOIN PEN ON FIN.NUNOTA = PEN.NUNOTA
inner join TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
inner join tgfven ven on fin.codvend = ven.codvend
WHERE FIN.CODTIPOPER IN (1000, 1003, 1013, 1111, 1005) AND FIN.DHBAIXA IS NULL 
AND (CASE WHEN FIN.AD_TIPOCOBRANCA IS NULL THEN 'Vazio' ELSE FIN.AD_TIPOCOBRANCA END) = :A_AD_TIPOCOBRANCA
AND ((FIN.DTVENC >= :P_DTVENC.INI AND FIN.DTVENC <= :P_DTVENC.FIN) OR (:P_DTVENC.INI IS NULL AND :P_DTVENC.FIN IS NULL))
AND (FIN.NUNOTA = :P_NUNOTA OR :P_NUNOTA IS NULL)
AND (FIN.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)
GROUP BY FIN.AD_TIPOCOBRANCA,FIN.NUNOTA,FIN.NUMNOTA,FIN.CODPARC,PAR.RAZAOSOCIAL,fin.codvend,ven.apelido




--- multilist vendedor


SELECT DISTINCT
	fin.codvend VALUE,
	fin.codvend||' - '||ven.apelido LABEL
FROM tgffin FIN
inner join TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
inner join tgfven ven on fin.codvend = ven.codvend
WHERE FIN.CODTIPOPER IN (1000, 1003, 1013, 1111, 1005) AND FIN.DHBAIXA IS NULL
GROUP BY fin.codvend,ven.apelido ORDER BY 2


