
----cartao
WITH
ite1 AS (SELECT ite.nunota,sum(ite.VLRTOT)VLRTOT FROM tgfite ite GROUP BY ite.nunota),
COM AS (SELECT DISTINCT VALOR, OPCAO FROM TDDCAM CAM INNER jOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB = 'TGFCAB' AND CAM.NOMECAMPO = 'TIPMOV' ORDER BY OPC.ORDEM)
SELECT
CAB.CODEMP,
CAB.TIPMOV,
COM.OPCAO,
TO_CHAR(CAB.DTNEG, 'MM/YYYY') AS PERIODO,
TO_CHAR(CAB.DTNEG, 'YYYY') AS ANO,
TO_CHAR(CAB.DTNEG, 'MM') AS MES,
SUM(CASE WHEN CAB.NUMCOTACAO IS NULL THEN (CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) ELSE 0 END) AS COMPRA_DIRETA,
SUM(CASE WHEN CAB.NUMCOTACAO IS NOT NULL THEN (CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) ELSE 0 END) AS TIME_SUPRIMENTOS,
sum(CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) vlrnota
FROM tgfite ite 
INNER JOIN ite1 ON ite.nunota = ite1.nunota
INNER JOIN tgfcab cab ON ite1.nunota = cab.nunota
INNER JOIN com ON cab.tipmov = com.valor
WHERE cab.TIPMOV ='O'
AND EXTRACT(MONTH FROM CAB.DTNEG) = EXTRACT(MONTH FROM SYSDATE)
AND EXTRACT(YEAR FROM CAB.DTNEG) = EXTRACT(YEAR FROM SYSDATE)
GROUP BY CAB.CODEMP, CAB.TIPMOV, COM.OPCAO, TO_CHAR(CAB.DTNEG, 'MM/YYYY'), TO_CHAR(CAB.DTNEG, 'YYYY'), TO_CHAR(CAB.DTNEG, 'MM')





--RESUMO - COMPRAS DIRETAS X TIME SUPRIMENTOS
WITH
ite1 AS (SELECT ite.nunota,sum(ite.VLRTOT)VLRTOT FROM tgfite ite GROUP BY ite.nunota),
COM AS (SELECT DISTINCT VALOR, OPCAO FROM TDDCAM CAM INNER jOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB = 'TGFCAB' AND CAM.NOMECAMPO = 'TIPMOV' ORDER BY OPC.ORDEM)
SELECT
CAB.CODEMP,
CAB.TIPMOV,
COM.OPCAO,
TO_CHAR(CAB.DTNEG, 'MM/YYYY') AS PERIODO,
TO_CHAR(CAB.DTNEG, 'YYYY') AS ANO,
TO_CHAR(CAB.DTNEG, 'MM') AS MES,
SUM(CASE WHEN CAB.NUMCOTACAO IS NULL THEN (CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) ELSE 0 END) AS COMPRA_DIRETA,
SUM(CASE WHEN CAB.NUMCOTACAO IS NOT NULL THEN (CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) ELSE 0 END) AS TIME_SUPRIMENTOS,
sum(CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) vlrnota
FROM tgfite ite 
INNER JOIN ite1 ON ite.nunota = ite1.nunota
INNER JOIN tgfcab cab ON ite1.nunota = cab.nunota
INNER JOIN com ON cab.tipmov = com.valor
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIGRU GRU ON USU.CODGRUPO = GRU.CODGRUPO
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU1 ON PRO.CODGRUPOPROD = GRU1.CODGRUPOPROD
INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
WHERE cab.TIPMOV ='O'
AND ((CAB.DTNEG >= :P_PERIODO.INI AND CAB.DTNEG <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
AND CAB.CODEMP IN :P_CODEMP AND PRO.CODGRUPOPROD IN :P_GRUPO_PRODUTO
GROUP BY CAB.CODEMP, CAB.TIPMOV, COM.OPCAO, TO_CHAR(CAB.DTNEG, 'MM/YYYY'), TO_CHAR(CAB.DTNEG, 'YYYY'), TO_CHAR(CAB.DTNEG, 'MM')
ORDER BY TO_CHAR(CAB.DTNEG,'YYYY')DESC,TO_CHAR(CAB.DTNEG,'MM')DESC






--DETALHAMENTO - COMPRAS DIRETAS X TIME SUPRIMENTOS
WITH
ite1 AS (SELECT ite.nunota,sum(ite.VLRTOT)VLRTOT FROM tgfite ite GROUP BY ite.nunota),
COM AS (SELECT DISTINCT VALOR, OPCAO FROM TDDCAM CAM INNER jOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB = 'TGFCAB' AND CAM.NOMECAMPO = 'TIPMOV' ORDER BY OPC.ORDEM)
SELECT
CAB.TIPMOV,
COM.OPCAO,
CAB.NUMCOTACAO,
CASE WHEN CAB.NUMCOTACAO IS NULL THEN 'COMPRA DIRETA' ELSE 'TIME SUPRIMENTOS' END SITUACAO,
CAB.NUNOTA,
CAB.NUMNOTA,
TO_CHAR(CAB.DTNEG,'MM/YYYY')PERIODO,
CAB.DTNEG,
CAB.DTFATUR,
CAB.DTENTSAI,
CAB.DTMOV,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
sum(CASE WHEN ite.vlrtot = 0 THEN 0 ELSE (ite.vlrtot/ite1.vlrtot)*cab.vlrnota END) vlrnota,
CAB.CODUSUINC,
USU.NOMEUSU USU_INCLUSAO,
GRU.NOMEGRUPO,
CAB.CODVEND COD_COMPRADOR,
VEN.APELIDO COMPRADOR
FROM tgfite ite 
INNER JOIN ite1 ON ite.nunota = ite1.nunota
INNER JOIN tgfcab cab ON ite1.nunota = cab.nunota
INNER JOIN com ON cab.tipmov = com.valor
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
INNER JOIN TSIGRU GRU ON USU.CODGRUPO = GRU.CODGRUPO
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU1 ON PRO.CODGRUPOPROD = GRU1.CODGRUPOPROD
INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND
WHERE cab.TIPMOV ='O'
AND TO_CHAR(CAB.DTNEG,'MM/YYYY') = :A_PERIODO AND CAB.CODEMP = :A_CODEMP
AND ((CAB.DTNEG >= :P_PERIODO.INI AND CAB.DTNEG <= :P_PERIODO.FIN)
OR (:P_PERIODO.INI IS NULL AND :P_PERIODO.FIN IS NULL))
AND CAB.CODEMP IN :P_CODEMP AND PRO.CODGRUPOPROD IN :P_GRUPO_PRODUTO
AND CAB.CODUSUINC IN :P_USU_INCLUSAO AND CAB.CODVEND IN :P_USU_COMPRADOR
GROUP BY
CAB.TIPMOV,
COM.OPCAO,
CAB.NUMCOTACAO,
CASE WHEN CAB.NUMCOTACAO IS NULL THEN 'COMPRA DIRETA' ELSE 'TIME SUPRIMENTOS' END,
CAB.NUNOTA,
CAB.NUMNOTA,
TO_CHAR(CAB.DTNEG,'MM/YYYY'),
CAB.DTNEG,
CAB.DTFATUR,
CAB.DTENTSAI,
CAB.DTMOV,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
CAB.CODUSUINC,
USU.NOMEUSU,
GRU.NOMEGRUPO
ORDER BY CAB.NUNOTA



SELECT * FROM TSIGRU GRU
SELECT * FROM TDDCAM CAM WHERE CAM.NOMETAB='TGFCAB' AND CAM.NOMECAMPO='TIPMOV'
SELECT * FROM TDDOPC OPC

SELECT VALOR,OPCAO 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFCAB' AND CAM.NOMECAMPO='TIPMOV'
ORDER BY OPC.ORDEM




---FILTRO MULTILIST EMPRESA
SELECT DISTINCT 
CAB.CODEMP VALUE,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL LABEL
FROM TGFCAB CAB 
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
WHERE 
CAB.TIPMOV = 'O'

-- FILTRO GRUPO PRODUTO
SELECT 
PRO.CODGRUPOPROD VALUE,
PRO.CODGRUPOPROD||' - '||GRU.DESCRGRUPOPROD LABEL
FROM TGFCAB CAB 
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE 
CAB.TIPMOV = 'O'
GROUP BY PRO.CODGRUPOPROD,GRU.DESCRGRUPOPROD
ORDER BY GRU.DESCRGRUPOPROD

-- FILTRO USURIO INCLUSAO
WITH
ite1 AS (SELECT ite.nunota,sum(ite.VLRTOT)VLRTOT FROM tgfite ite GROUP BY ite.nunota)
SELECT
CAB.CODUSUINC VALUE,
CAB.CODUSUINC||' - '||USU.NOMEUSU LABEL
FROM tgfite ite 
INNER JOIN ite1 ON ite.nunota = ite1.nunota
INNER JOIN tgfcab cab ON ite1.nunota = cab.nunota
INNER JOIN TSIUSU USU ON CAB.CODUSUINC = USU.CODUSU
WHERE cab.TIPMOV ='O'
GROUP BY CAB.CODUSUINC,USU.NOMEUSU
ORDER BY 2

--FILTRO COMPRADOR
SELECT 
CAB.CODVEND VALUE,
CAB.CODVEND||' - '||VEN.APELIDO LABEL
FROM TGFCAB CAB 
INNER JOIN TGFVEN VEN ON CAB.CODVEND = VEN.CODVEND 
WHERE 
CAB.TIPMOV = 'O'
GROUP BY CAB.CODVEND,VEN.APELIDO
ORDER BY 2