SELECT * FROM TGCPAR
SELECT * FROM TSILIM
SELECT * FROM TSILIB
WHERE NUCHAVE = 13751
SELECT * FROM TFPAUT
SELECT * FROM TGFCAB WHERE NUNOTA = 13751

SELECT DISTINCT 
        PAR.CODPARC, 
        VEN.APELIDO,
        PAR.CODVEND,
        PAR.RAZAOSOCIAL,
		PAR.LIMCRED,
        PAR.LIMCREDMENSAL,
       ROUND( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)),2) AS "TOT_LIQ",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/:P_DIAS),2) "MedDia",
       ROUND(((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))*1.3)/:P_DIAS),2) "addPercentualDia",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/(:P_DIAS/30)),2) "Periodo",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/(:P_DIAS/30)*1.3),2) "addPeriodo"
FROM 
TGFPAR PAR, TGFITE ITE, TGFCAB CAB, TGFVEN VEN  
WHERE PAR.CODPARC = CAB.CODPARC
AND CAB.NUNOTA = ITE.NUNOTA
AND TO_DATE(CAB.DTFATUR, 'DD/MM/YY') >=SYSDATE-90
AND TO_DATE(CAB.DTFATUR, 'DD/MM/YY') <=SYSDATE-1
AND CAB.TIPMOV IN ('V')
AND PAR.CODVEND IN :P_CODVEND
AND PAR.CODVEND = VEN.CODVEND
AND PAR.CLIENTE='S'
GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO,PAR.CODVEND,PAR.LIMCRED,PAR.LIMCREDMENSAL
ORDER BY PAR.RAZAOSOCIAL

SELECT DISTINCT 
PAR.CODPARC, 
CASE WHEN VEN.APELIDO='<SEM VENDEDOR>' THEN 'SEM CADASTRO'ELSE VEN.APELIDO END APELIDO,
PAR.CODVEND,
--CASE WHEN VEN.TIPVEND IS NULL THEN 'SEM CADASTRO' ELSE VEN.TIPVEND END VEN.TIPVEND,
PAR.CODPARC,
PAR.RAZAOSOCIAL,
PAR.LIMCRED,
PAR.LIMCREDMENSAL
FROM TGFPAR PAR
INNER JOIN TGFVEN VEN ON PAR.CODVEND = VEN.CODVEND
WHERE PAR.LIMCRED IS NOT NULL



SELECT * FROM TGFVEN
SELECT * FROM TDDCAM WHERE NOMETAB= 'TGFVEN' AND NOMECAMPO = 'TIPVEND'



SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFVEN' AND CAM.NOMECAMPO='TIPVEND'
ORDER BY OPC.ORDEM