SELECT DISTINCT
EXC.CODEMPNEGOC,
EXC.NUNOTA,
EXC.NUMNOTA,
EXC.VLRNOTA,
EXC.CODPARC,
PAR.RAZAOSOCIAL,
EXC.DHEXCLUSAO,
EXC.CODUSU,
USU.NOMEUSU
FROM TGFCAB_EXC EXC
INNER JOIN TSIUSU USU ON EXC.CODUSU = USU.CODUSU
INNER JOIN TGFPAR PAR ON EXC.CODPARC = PAR.CODPARC


SELECT DISTINCT
EXC.CODUSU,
USU.NOMEUSU,
COUNT(EXC.CODUSU) TOTAL_EXCLUSOES
FROM TGFCAB_EXC EXC
INNER JOIN TSIUSU USU ON EXC.CODUSU = USU.CODUSU
INNER JOIN TGFPAR PAR ON EXC.CODPARC = PAR.CODPARC
GROUP BY EXC.CODUSU, USU.NOMEUSU
WHERE (EXC.NUMNOTA = :P_NUMNOTA OR :P_NUMNOTA IS NULL)
