
WITH 
BCO1 AS (SELECT CODCTABCOINT,DESCRICAO FROM TSICTA),
BCO2 AS (SELECT CODBCO,DESCRICAO FROM TSICTA)
SELECT DISTINCT
FIN.NUFIN AS NU_UNICO,
FIN.RECDESP,
'Cód. Conta: '||FIN.CODCTABCOINT||' - Descrição '||BCO1.DESCRICAO AS CONTA_BAIXA,
FIN.CODBCO AS BANCO,
BCO2.DESCRICAO AS DESCRICAO_BANCO,
SUM(
(NVL(FIN.VLRDESDOB,0) +
(CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA,0) ELSE 0 END) +
(CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO,0) ELSE 0 END) +
NVL(FIN.DESPCART,0) +
NVL(FIN.VLRVENDOR,0) -
NVL(FIN.VLRDESC,0) -
(CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF,0) ELSE 0 END) -
(CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS,0) ELSE 0 END) -
(CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS,0) ELSE 0 END) -
NVL(FIN.CARTAODESC,0) +
NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP),2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN),0) +
NVL(FIN.VLRMULTANEGOC,0) +
NVL(FIN.VLRJURONEGOC,0) -
NVL(FIN.VLRMULTALIB,0) -
NVL(FIN.VLRJUROLIB,0) +
NVL(FIN.VLRVARCAMBIAL,0)) * NVL(FIN.RECDESP,0)
) AS VLRLIQUIDO
FROM TGFFIN FIN
INNER JOIN BCO1 ON FIN.CODCTABCOINT = BCO1.CODCTABCOINT
INNER JOIN BCO2 ON FIN.CODBCO = BCO2.CODBCO
WHERE FIN.RECDESP = 1 AND FIN.CODBCO NOT IN (9999,999)
GROUP BY
FIN.NUFIN,
FIN.RECDESP,
FIN.CODCTABCOINT,
BCO1.DESCRICAO,
FIN.CODBCO,
BCO2.DESCRICAO

