--Dash de Venda Entrega Futura Sintético

SELECT DISTINCT
CAB.CODPARC,
PAR.CGC_CPF,
PAR.NOMEPARC,
PAR.RAZAOSOCIAL,
SUM(CASE 
WHEN CAB.CODTIPOPER IN (1111,1117,1216) THEN (ITE.QTDNEG)
WHEN CAB.CODTIPOPER IN (1112,1152,1153,1213) THEN (ITE.QTDNEG * -1)
END) QTDNEG,
AVG(ITE.VLRUNIT) VLRUNIT,
SUM(CASE
WHEN CAB.CODTIPOPER IN (1111,1117,1216) THEN ITE.VLRTOT
WHEN CAB.CODTIPOPER IN (1112,1152,1153,1213) THEN ITE.VLRTOT * -1
END) AS VLRTOT

FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC

WHERE
(CAB.DTNEG >= :P_PERIODO.INI AND CAB.DTNEG <= :P_PERIODO.FIN)
AND CAB.CODEMP = :P_EMPRESA
AND CAB.CODTIPOPER IN :P_TOP
AND (CAB.CODPARC = :P_PARCEIRO OR :P_PARCEIRO IS NULL)

GROUP BY
CAB.CODPARC,
PAR.CGC_CPF,
PAR.NOMEPARC,
PAR.RAZAOSOCIAL

ORDER BY
PAR.RAZAOSOCIAL


-------

