--D0026 – DASH  VENDA FUTURA E REMESSAS
--RELACAO DE NOTAS PARA DESCONTO DE DUPLICATAS
--NOTAS DE VENDA ENTREGA FUTURA E REMESSA
--RELACAO DE NOTAS ENTREGUES COM PENDENCIA DE VALOR A RECEBER
WITH TEST AS(
SELECT
NUNOTAORIG,
SUM(QTDATENDIDA) QTDATENDIDA
FROM TGFVAR
GROUP BY
NUNOTAORIG
ORDER BY
NUNOTAORIG)



SELECT DISTINCT
CAB.NUNOTA,
CAB.CODTIPOPER,
TOP.DESCROPER,
CAB.NUMNOTA,
CAB.DTNEG,
CAB.DTMOV,
FIN.DTVENC,
FIN.DHBAIXA,
CASE WHEN ((ITE.QTDNEG) - (TES.QTDATENDIDA))=0 THEN 'OK' ELSE 'PENDENTE' END STATUS,
ITE.QTDNEG,
TES.QTDATENDIDA,
(ITE.QTDNEG) - (TES.QTDATENDIDA) PENDENTE,
CAB.VLRNOTA
FROM
TGFCAB CAB
INNER JOIN TGFFIN FIN ON CAB.NUNOTA = FIN.NUNOTA
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
LEFT JOIN TEST TES ON CAB.NUNOTA = TES.NUNOTAORIG

WHERE
CAB.TIPMOV = 'V'
AND FIN.DHBAIXA IS NULL
AND ((ITE.QTDNEG) - (TES.QTDATENDIDA))=0

ORDER BY
FIN.DTVENC




------------------------------

WITH TEST AS(
SELECT
CAB.TIPMOV,
CAB.NUNOTA,
CAB.CODTIPOPER,
CAB.NUMNOTA,
CAB.VLRNOTA,
SUM(QTDNEG) QTDNEG
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
GROUP BY
CAB.TIPMOV,
CAB.NUNOTA,
CAB.CODTIPOPER,
CAB.NUMNOTA,
CAB.VLRNOTA
)



SELECT
VAR.NUNOTA,
VAR.NUNOTAORIG,
TES.TIPMOV,
TES.NUMNOTA,
TES.VLRNOTA,
SUM(QTDATENDIDA) QTDATENDIDA
FROM 
TGFVAR VAR
INNER JOIN TEST TES ON VAR.NUNOTA = TES.NUNOTA
WHERE
TES.TIPMOV = 'V'
AND VAR.NUNOTAORIG = :A_NUNOTAORIG
GROUP BY
VAR.NUNOTA,
VAR.NUNOTAORIG,
TES.TIPMOV,
TES.NUMNOTA,
TES.VLRNOTA

