----Dash de Venda Entrega Futura Analitico
SELECT DISTINCT
CAB.NUNOTA,
CAB.AD_NUNOTAPED,
CAB.NUMNOTA,
CAB.DTNEG,
CAB.DTFATUR,
CAB.DTENTSAI,
CAB.DTMOV,
CAB.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",
CAB.CODTIPVENDA,
TPV.DESCRTIPVENDA,
CAB.CODTIPOPER TOPS,
TOP.DESCROPER DESCRTOP,
(CASE
WHEN (UFS.UF = 'MG') THEN TOP.CODCFO_SAIDA
WHEN (UFS.UF <> 'MG') THEN TOP.CODCFO_SAIDA_FORA
END) AS "CFOP",


CAB.TIPMOV,

(CASE 
WHEN CAB.CODTIPOPER IN (1111,1117,1216) THEN (ITE.QTDNEG)
WHEN CAB.CODTIPOPER IN (1112,1152,1153,1213) THEN (ITE.QTDNEG * -1)
END) AS QTDNEG,
ITE.VLRUNIT,
(CASE
WHEN CAB.CODTIPOPER IN (1111,1117,1216) THEN ITE.VLRTOT
WHEN CAB.CODTIPOPER IN (1112,1152,1153,1213) THEN ITE.VLRTOT * -1
END) AS VLRTOT


FROM
TGFCAB CAB

INNER JOIN TGFTPV TPV ON CAB.CODTIPVENDA = TPV.CODTIPVENDA
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER


WHERE
AND CAB.CODTIPOPER IN :P_TOP
AND CAB.CODPARC = :A_CODPARC
AND (DTNEG >= :P_PERIODO.INI AND DTNEG <= :P_PERIODO.FIN)


ORDER BY
PARCEIRO,
DTENTSAI
