SELECT * FROM TGCPAR
SELECT * FROM TSILIM
SELECT * FROM TSILIB
WHERE NUCHAVE = 13751
SELECT * FROM TFPAUT
SELECT * FROM TGFCAB WHERE NUNOTA = 13751

SELECT DISTINCT 
        PAR.CODPARC, 
        VEN.APELIDO,
        PAR.CODVEND,
        PAR.RAZAOSOCIAL,
		PAR.LIMCRED,
        PAR.LIMCREDMENSAL,
       ROUND( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)),2) AS "TOT_LIQ",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/:P_DIAS),2) "MedDia",
       ROUND(((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))*1.3)/:P_DIAS),2) "addPercentualDia",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/(:P_DIAS/30)),2) "Periodo",
       ROUND((( (SUM(ITE.VLRTOT))-( SUM(ITE.VLRDESC)))/(:P_DIAS/30)*1.3),2) "addPeriodo"
FROM 
        TGFPAR PAR,
        TGFITE ITE, 
        TGFCAB CAB,
        TGFVEN VEN  
WHERE PAR.CODPARC = CAB.CODPARC
AND CAB.NUNOTA = ITE.NUNOTA
AND TO_DATE(CAB.DTFATUR, 'DD/MM/YY') >=SYSDATE-90
AND TO_DATE(CAB.DTFATUR, 'DD/MM/YY') <=SYSDATE-1
AND CAB.TIPMOV IN ('V')
AND PAR.CODVEND IN :P_CODVEND
AND PAR.CODVEND = VEN.CODVEND
AND PAR.CLIENTE='S'

GROUP BY PAR.CODPARC, PAR.RAZAOSOCIAL, VEN.APELIDO,PAR.CODVEND,PAR.LIMCRED,PAR.LIMCREDMENSAL
ORDER BY PAR.RAZAOSOCIAL