
SELECT * FROM TGFFAI


SELECT * FROM TGFINSSRPA
SELECT * FROM TGFINSSREF


SELECT 
FIN.NUFIN, 
FIN.NUMNOTA, 
FIN.CODPARC, 
PAR.RAZAOSOCIAL, 
FIN.DTNEG, 
FIN.DHBAIXA, 
FIN.VLRDESDOB, 
FIN.VLRJURO, 
FIN.VLRMULTA, 
FIN.VLRDESC, 
FIN.VLRBAIXA, 
FIN.HISTORICO, 
FIN.VLRDESDOB * PC.ALIQPIS / 100 AS PIS,
FIN.VLRDESDOB * PC.ALIQCOFINS / 100 AS COFINS
 FROM TGFFIN FIN, TGFPAR PAR, TGFNATPC PC, TGFNATPCEMP E
WHERE FIN.CODPARC = PAR.CODPARC
  AND FIN.CODNAT = PC.CODNAT
  AND PC.NUNATPISCOF = E.NUNATPISCOF
  AND E.CODEMP = FIN.CODEMP
  AND FIN.RECDESP = 1
  AND FIN.ORIGEM = 'E'
  AND FIN.NURENEG IS NULL
  AND FIN.PROVISAO = 'N'
  AND (FIN.DHBAIXA >= TO_DATE('01-04-2023','DD-MM-YYYY')
  AND FIN.DHBAIXA <= TO_DATE('30-04-2023','DD-MM-YYYY'))
  AND FIN.DHBAIXA IS NOT NULL
  AND (FIN.CODEMP = 60)
  AND FIN.CODTIPOPERBAIXA NOT IN (1404)
  AND FIN.CODTIPOPER NOT IN (301,305,1302)
  AND FIN.CODNAT IN (1010100,1010200)


SELECT * FROM TGFVEN t  
  
SELECT
BEM.CODEMP,
BEM.CODBEM,
BEM.CODPROD,
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD, 
BEM.VLRDEP,
BEM.VLRSALDO,
BEM.DESCRABREV,
BEM.VLRAQUISICAO
FROM TCIBEM BEM
INNER JOIN TGFPRO PRO ON BEM.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
WHERE CODBEM <>'<TODOS>'


SELECT * FROM TGFVEI t WHERE MARCAMODELO LIKE '%CA%'
SELECT RAZAOSOCIAL AS NOME_PARCEIRO FROM TGFPAR  WHERE ROWNUM = 1


SELECT 
CAB.DTMOV,
CAB.DTENTSAI,
CAB.CODEMP,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
ITE.CODPROD,
PRO.DESCRPROD, 
ITE.QTDNEG,
ITE.VLRUNIT, 
ITE.VLRTOT, 
CAB.AD_UMIDADE 
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE CAB.AD_UMIDADE > 0



SELECT 
TO_CHAR(CAB.DTMOV,'YYYY'),
TO_CHAR(CAB.DTMOV,'MM'),
TO_CHAR(CAB.DTMOV,'MM-YYYY') DTMOV,
CAB.CODEMP,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
ITE.CODPROD,
PRO.DESCRPROD, 
SUM(ITE.QTDNEG),
AVG(ITE.VLRUNIT), 
SUM(ITE.VLRTOT), 
AVG(CAB.AD_UMIDADE)
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
WHERE CAB.AD_UMIDADE > 0
GROUP BY
TO_CHAR(CAB.DTMOV,'YYYY'),
TO_CHAR(CAB.DTMOV,'MM'),
TO_CHAR(CAB.DTMOV,'MM-YYYY'),
CAB.CODEMP,
CAB.CODPARC,
PAR.RAZAOSOCIAL,
ITE.CODPROD,
PRO.DESCRPROD




SELECT DISTINCT
	FIN.NUFIN, 
	FIN.NUMNOTA, 
	FIN.CODPARC, 
	PAR.RAZAOSOCIAL, 
	FIN.DTNEG, 
	FIN.DHBAIXA, 
	FIN.VLRDESDOB, 
	FIN.VLRJURO, 
	FIN.VLRMULTA, 
	FIN.VLRDESC, 
	FIN.VLRBAIXA, 
	FIN.HISTORICO
 FROM TGFFIN FIN, TGFPAR PAR, TGFNATPC PC, TGFNATPCEMP E
WHERE FIN.CODPARC = PAR.CODPARC
  AND FIN.CODNAT = PC.CODNAT
  AND PC.NUNATPISCOF = E.NUNATPISCOF
  AND E.CODEMP = FIN.CODEMP
  AND FIN.RECDESP = 1
  AND FIN.NURENEG IS NULL
  AND FIN.PROVISAO = 'N'
  AND (FIN.DHBAIXA >= TO_DATE('01-04-2023','DD-MM-YYYY')
  AND FIN.DHBAIXA <= TO_DATE('30-04-2023','DD-MM-YYYY'))
  AND FIN.DHBAIXA IS NOT NULL
  AND (FIN.CODEMP = 60)
  AND FIN.CODTIPOPERBAIXA NOT IN (1404)
  AND FIN.CODTIPOPER NOT IN (301,305,1302)
  AND FIN.CODNAT IN (1010100,1010200)  
  
  
  
  SELECT NOMEPARC AS NOME_PARCEIRO FROM TGFPAR  WHERE RAZAOSOCIAL  LIKE  '%DIOGO MERC%' ORDER BY CODPARC ASC
 
  SELECT RAZAOSOCIAL AS NOME_PARCEIRO FROM TGFPAR  WHERE RAZAOSOCIAL  LIKE  '%DIOGO MERC%'

  
  