SELECT DISTINCT
CAB.CODEMP AS VALUE,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL AS LABEL
FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
GROUP BY
CAB.CODEMP,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL
ORDER BY 1


SELECT *
FROM TDDCAM
WHERE 
NOMECAMPO = 'TIPMOV'


SELECT TO_CHAR(DTNEG,'YYYY')ANO,TO_CHAR(DTNEG,'MM')MES,TO_CHAR(DTNEG,'MM-YYYY')COMP,COUNT(NUFIN)QTD FROM TGFFIN 
GROUP BY TO_CHAR(DTNEG,'YYYY'),TO_CHAR(DTNEG,'MM'),TO_CHAR(DTNEG,'MM-YYYY')
ORDER BY 1,2


SELECT NUFIN, 
       NUFIN - LAG(NUFIN) OVER (ORDER BY NUFIN) AS A
FROM TGFFIN

SELECT NUNOTA, 
       NUNOTA - LAG(NUNOTA) OVER (ORDER BY NUNOTA) AS A
FROM TGFCAB


--acompanhamento pedido
SELECT * FROM TGFACT WHERE NUNOTA = 13491

TGFEAC 




SELECT  DISTINCT
to_CHAR(CAB.DTMOV,'YYYY') ANO,
to_CHAR(CAB.DTMOV,'MM')MES,
CAB.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC,
SUM(CASE WHEN CAB.CODTIPOPER IN (1100,1112,1152) THEN VLRNOTA  ELSE 0 END) AS Saidas,
SUM(CASE WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN VLRNOTA * -1 ELSE 0 END) AS Devolucoes,
SUM(CASE WHEN CAB.CODTIPOPER IN (1105) THEN VLRNOTA ELSE 0  END) AS Servicos,
SUM(CASE WHEN CAB.CODTIPOPER IN (1100,1112,1152) THEN VLRNOTA  ELSE 0 END) +
SUM(CASE WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN VLRNOTA * -1 ELSE 0 END) +
SUM(CASE WHEN CAB.CODTIPOPER IN (1105) THEN VLRNOTA ELSE 0  END) AS Total
FROM
TGFCAB CAB
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TSIEND ENDI on EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI on EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID on EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE 
(CAB.DTMOV  >=  TO_DATE('01-04-2023','DD-MM-YYYY') AND  CAB.DTMOV <= TO_DATE('30-04-2023','DD-MM-YYYY'))
AND CAB.CODTIPOPER IN (1100,1112,1152,1200,1201,1216,1217,1105)
AND CAB.CODEMP = 60
AND CAB.STATUSNOTA = 'L'
GROUP BY
to_CHAR(CAB.DTMOV,'YYYY'),
to_CHAR(CAB.DTMOV,'MM'),
CAB.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC
ORDER BY 1,2



SELECT
NUNOTA 
FROM
TCIBEM t
WHERE NUNOTA <> 0

SELECT * FROM TGFTOP
WHERE CODTIPOPER IN (301,305,1302)

SELECT * FROM TGFCAB

SELECT CODNAT  FROM TGFFIN WHERE ORIGEM ='E'

SELECT
BEM.NUNOTA,
BEM.NUMNOTA,
TO_CHAR(MOV.REFERENCIA,'MM-YYYY') COMP,
BEM.CODBEM,
BEM.DESCRABREV,
BEM.CODPROD,
PRO.DESCRPROD,
MOV.VLRDEP 
FROM TCIBEM BEM
INNER JOIN TGFPRO PRO ON BEM.CODPROD = PRO.CODPROD
INNER JOIN TCIMOV MOV ON BEM.CODBEM = MOV.CODBEM



SELECT DISTINCT
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 2




SELECT DISTINCT
CAB.NATUREZAOPERDES 
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.DTENTSAI,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM,
ITE.CODPROD,
PRO.DESCRPROD,
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
ITE.VLRTOT
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 3


SELECT CODVEICULO,MARCAMODELO,PLACA, CHASSIS  FROM TGFVEI ORDER BY 1



SELECT * FROM TGFRAT

SELECT
*
FROM TGFVEI



SELECT * FROM TGFCAB



SELECT * FROM TGFPRO WHERE DESCRPROD LIKE '%VAGEM%'

SELECT * FROM TGFGRU
SELECT * FROM TCIBEM
SELECT * FROM TCICTE
SELECT * FROM TCIMOV
SELECT * FROM TGFCAB
SELECT * FROM TCICABCTE
SELECT * FROM TCBLAN LAN

AND LAN.NUMLOTE NOT IN (9999)



SELECT 
PRO.CODPROD,
PRO.DESCRPROD,
GRU.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'


SELECT 
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'
GROUP BY 
GRU.DESCRGRUPOPROD,
PRO.USOPROD


SELECT * FROM TGFITE


--RELATORIO DE FATURAMENTO - INTERVALO DE DATAS POR DTNEG

SELECT DISTINCT
CAB.CODTIPOPER TOPS,
TOP.DESCROPER DESCRTOP,
(CASE
WHEN (UFS.UF = 'MG') THEN TOP.CODCFO_SAIDA
WHEN (UFS.UF <> 'MG') THEN TOP.CODCFO_SAIDA_FORA
END) AS "CFOP",
UFS.UF,
CAB.NUMNOTA,
ITE.SEQUENCIA,
CAB.DTFATUR,
CAB.DTENTSAI,
CAB.DTMOV DTMOV,
CAB.DTNEG,
CAB.CODEMP,
EMP.RAZAOSOCIAL "EMPRESA",
CAB.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",
CAB.TIPMOV,
ITE.CODPROD,
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD,
ITE.CODTRIB,
PRO.NCM,
PRO.CODVOL,



(CASE
WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN ITE.QTDNEG * -1
WHEN CAB.CODTIPOPER IN (1100,1112,1152,1105,1153) THEN ITE.QTDNEG END) AS QTDNEG,
TTLQTDE,
ITE.VLRUNIT,


(CASE
WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN ITE.VLRTOT * -1
WHEN CAB.CODTIPOPER IN (1100,1112,1152,1105,1153) THEN ITE.VLRTOT END) AS VLRTOT,


(
(CASE
WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN ITE.QTDNEG * -1
WHEN CAB.CODTIPOPER IN (1100,1112,1152,1105,1153) THEN ITE.QTDNEG END)
/TTLQTDE) AS PART_PERC_QTD_NO_PROD,
CAB.VLRNOTA,

(((CASE
WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN ITE.QTDNEG * -1
WHEN CAB.CODTIPOPER IN (1100,1112,1152,1105,1153) THEN ITE.QTDNEG END)
/TTLQTDE) * CAB.VLRNOTA) AS VLR_PROP_PROD


FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN (SELECT ITE.NUNOTA, SUM(QTDNEG) AS TTLQTDE
FROM TGFITE ITE GROUP BY ITE.NUNOTA) ITE2 ON ITE.NUNOTA = ITE2.NUNOTA
WHERE (CAB.DTNEG >= :P_PERIODO.INI AND CAB.DTNEG <= :P_PERIODO.FIN)
AND CAB.CODEMP IN (:P_EMPRESA)
AND CAB.CODTIPOPER  IN (1100,1112,1152,1200,1201,1216,1217,1105,1153)
AND CAB.STATUSNOTA = 'L'
ORDER BY ITE.CODPROD,CAB.TIPMOV DESC, CAB.DTNEG


SELECT * FROM TCBIMP


SELECT VLRFRETE FROM TGFCAB WHERE VLRFRETE > 0
