--DRE

SELECT DISTINCT
TO_CHAR(LAN.DTMOV,'MM-YYYY')EXERCICIO,
LPAD(PLA.CTACTB,10)E,
CASE WHEN LPAD(PLA.CTACTB,1) = 3 THEN '5.03.01.01.0003' ELSE PLA.CTACTB END AS N,
PLA.CODCTACTB,
PLA.CTACTB,
PLA.DESCRCTA,
SUM(CASE WHEN LAN.TIPLANC='R' THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D' THEN -1*LAN.VLRLANC END) VLRLANC,

SUM(SELECT 
CASE WHEN TIPLANC='R' THEN 1*VLRLANC WHEN TIPLANC='D' THEN -1*VLRLANC END
FROM TCBLAN
WHERE DTMOV >= ADD_MONTHS(TRUNC(SYSDATE, 'MONTH'), -2)
  AND DTMOV < TRUNC(SYSDATE, 'MONTH')) TESTE







FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE (TO_CHAR(LAN.DTMOV,'MM-YYYY') = :P_EXERCICIO)
AND LPAD(PLA.CTACTB,1) IN (3,5)
AND PLA.ANALITICA = 'S'
AND LAN.CODEMP = :P_EMPRESA
GROUP BY
TO_CHAR(LAN.DTMOV,'MM-YYYY'),
PLA.CODCTACTB,
PLA.CTACTB,
PLA.DESCRCTA,
LPAD(PLA.CTACTB,10),
CASE WHEN LPAD(PLA.CTACTB,1) = 3 THEN '5.03.01.01.0003' ELSE PLA.CTACTB END
ORDER BY 3,4