SELECT DISTINCT
    CASE WHEN LPAD(PLA.CTACTB,1) = 3 THEN '5.03.01.01.0003' ELSE PLA.CTACTB END AS N,
	PLA.CODCTACTB,
	PLA.CTACTB,
	PLA.DESCRCTA,
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 0) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 0) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M0",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-1",  
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-2",  
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-3",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-4",      
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-5",      
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-6",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -7) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -7) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-7",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -8) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -8) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-8",      
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -9) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -9) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-9",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -10) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -10) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-10",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-11",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "M-12"
FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE LAN.DTMOV >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
AND LPAD(PLA.CTACTB,1) IN (3,5)
AND PLA.ANALITICA = 'S'
AND LAN.CODEMP = :P_EMPRESA
GROUP BY 
	PLA.CODCTACTB,
	PLA.CTACTB,
	PLA.DESCRCTA
ORDER BY 1,2,3,4