SELECT DISTINCT
    CASE WHEN LPAD(PLA.CTACTB,1) = 3 THEN '5.03.01.01.0003' ELSE PLA.CTACTB END AS N,
	PLA.CODCTACTB,
	PLA.CTACTB,
	PLA.DESCRCTA,
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 0) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), 0) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MES_ATUAL",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -12) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_12",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_11",    
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -10) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -10) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_10",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -9) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -9) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_9",  
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -8) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -8) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_8",  
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -7) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -7) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_7",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -6) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_6",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -5) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_5",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -4) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_4",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -3) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_3",  
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -2) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MESES_ATRAS_2",
  SUM(CASE 
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) AND LAN.TIPLANC='R'THEN LAN.VLRLANC
  WHEN TRUNC(LAN.DTMOV, 'MM') = ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1) AND LAN.TIPLANC='D'THEN LAN.VLRLANC*-1 END) AS "MES_ATRAS_1"
  
FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE LAN.DTMOV >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -11)
AND LPAD(PLA.CTACTB,1) IN (3,5)
AND PLA.ANALITICA = 'S'
AND LAN.CODEMP = 60--:P_EMPRESA
GROUP BY 
	PLA.CODCTACTB,
	PLA.CTACTB,
	PLA.DESCRCTA
ORDER BY 1,2,3,4