
WITH CUS1 AS
(
    SELECT 
        CODEMP,
        CODLOCAL,
        CODPROD,
        DTATUAL,
        CUSSEMICM
    FROM 
    (
        SELECT 
            CODEMP,
            CODLOCAL,
            CODPROD,
            DTATUAL,
            CUSSEMICM,
            ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
        FROM tgfcus
    ) CUS 
    WHERE rn = 1
    ORDER BY CODPROD
)

SELECT DISTINCT 
    EST.CODEMP,
    EST.CODLOCAL,
    LOC.DESCRLOCAL,
    PRO.CODPROD,
    PRO.DESCRPROD AS PRODUTO,
    PRO.USOPROD AS USADO_COMO,
    EST.CONTROLE,
    PRO.CODVOL AS UNIDADE,
    EST.ESTOQUE,
    CUS1.CUSSEMICM,
    CUS1.CUSSEMICM * EST.ESTOQUE AS VLR_EST,
    EST.ESTMIN,
    EST.ESTMAX,
    PRO.ATIVO,
    GRU.DESCRGRUPOPROD,
    CASE WHEN EST.ESTOQUE < 0 THEN 'RED' END AS FGCOLOR
FROM 
    TGFPRO PRO
INNER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD)
INNER JOIN TGFLOC LOC ON (EST.CODLOCAL = LOC.CODLOCAL)
INNER JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD = GRU.CODGRUPOPROD)
LEFT JOIN CUS1 ON EST.CODPROD = CUS1.CODPROD  
WHERE 
    (EST.CODEMP = :EMPRESA OR :EMPRESA IS NULL)
    AND (LOC.CODLOCAL = :LOCAL OR :LOCAL IS NULL)
    AND (PRO.CODPROD = :PRODUTO OR :PRODUTO IS NULL)
    AND PRO.USOPROD <> 'S'
    AND EST.CODPARC = 0
ORDER BY EST.CODEMP,PRO.CODPROD, PRO.ATIVO






---MULTILIST PARA EMPRESA
WITH CUS1 AS
(   SELECT CODEMP,CODLOCAL,CODPROD,DTATUAL,CUSSEMICM
    FROM 
    (SELECT CODEMP, CODLOCAL, CODPROD, DTATUAL,CUSSEMICM,
     ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
     FROM tgfcus ) CUS 
    WHERE rn = 1
    ORDER BY CODPROD)
SELECT DISTINCT 
    EST.CODEMP VALUE,
    EST.CODEMP||' - '||EMP.RAZAOSOCIAL LABEL
FROM 
    TGFPRO PRO
INNER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD)
INNER JOIN TGFLOC LOC ON (EST.CODLOCAL = LOC.CODLOCAL)
INNER JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD = GRU.CODGRUPOPROD)
LEFT JOIN CUS1 ON EST.CODPROD = CUS1.CODPROD
INNER JOIN TSIEMP EMP ON EST.CODEMP = EMP.CODEMP
GROUP BY EST.CODEMP,EMP.RAZAOSOCIAL ORDER BY 1



---MULTILIST PARA LOCAL
WITH CUS1 AS
(   SELECT CODEMP,CODLOCAL,CODPROD,DTATUAL,CUSSEMICM
    FROM 
    (SELECT CODEMP, CODLOCAL, CODPROD, DTATUAL,CUSSEMICM,
     ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
     FROM tgfcus ) CUS 
    WHERE rn = 1
    ORDER BY CODPROD)
SELECT DISTINCT 
    EST.CODLOCAL VALUE,
    EST.CODLOCAL||' - '||LOC.DESCRLOCAL LABEL
FROM 
    TGFPRO PRO
INNER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD)
INNER JOIN TGFLOC LOC ON (EST.CODLOCAL = LOC.CODLOCAL)
INNER JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD = GRU.CODGRUPOPROD)
LEFT JOIN CUS1 ON EST.CODPROD = CUS1.CODPROD
GROUP BY EST.CODLOCAL,LOC.DESCRLOCAL ORDER BY 1


---MULTILIST PARA GRUPO PRODUTO
WITH CUS1 AS
(   SELECT CODEMP,CODLOCAL,CODPROD,DTATUAL,CUSSEMICM
    FROM 
    (SELECT CODEMP, CODLOCAL, CODPROD, DTATUAL,CUSSEMICM,
     ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
     FROM tgfcus ) CUS 
    WHERE rn = 1
    ORDER BY CODPROD)
SELECT DISTINCT 
    PRO.CODGRUPOPROD VALUE,
    PRO.CODGRUPOPROD ||' - '||GRU.DESCRGRUPOPROD LABEL
FROM 
    TGFPRO PRO
INNER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD)
INNER JOIN TGFLOC LOC ON (EST.CODLOCAL = LOC.CODLOCAL)
INNER JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD = GRU.CODGRUPOPROD)
LEFT JOIN CUS1 ON EST.CODPROD = CUS1.CODPROD
GROUP BY PRO.CODGRUPOPROD,GRU.DESCRGRUPOPROD ORDER BY 1



---MULTILIST PARA USADO COMO
WITH CUS1 AS
(   SELECT CODEMP,CODLOCAL,CODPROD,DTATUAL,CUSSEMICM
    FROM 
    (SELECT CODEMP, CODLOCAL, CODPROD, DTATUAL,CUSSEMICM,
     ROW_NUMBER() OVER (PARTITION BY CODPROD ORDER BY DTATUAL DESC) AS rn
     FROM tgfcus ) CUS 
    WHERE rn = 1
    ORDER BY CODPROD),
OPC1 AS 
(
SELECT VALOR,OPCAO 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFPRO' AND CAM.NOMECAMPO='USOPROD'
ORDER BY OPC.ORDEM
)    
SELECT DISTINCT 
	PRO.USOPROD VALUE,
	PRO.USOPROD ||' - '|| OPC1.OPCAO LABEL
FROM 
    TGFPRO PRO
INNER JOIN TGFEST EST ON (EST.CODPROD = PRO.CODPROD)
INNER JOIN TGFLOC LOC ON (EST.CODLOCAL = LOC.CODLOCAL)
INNER JOIN TGFGRU GRU ON (PRO.CODGRUPOPROD = GRU.CODGRUPOPROD)
LEFT JOIN CUS1 ON EST.CODPROD = CUS1.CODPROD
INNER JOIN OPC1 ON PRO.USOPROD = OPC1.VALOR
GROUP BY PRO.USOPROD,OPC1.OPCAO ORDER BY 1





SELECT VALOR,OPCAO 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFPRO' AND CAM.NOMECAMPO='USOPROD'
ORDER BY OPC.ORDEM