-- Calcular o faturamento bruto

SELECT DISTINCT
SUM(SUM(CASE WHEN LAN.TIPLANC='R' THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D' THEN -1*LAN.VLRLANC END)) OVER 
(ORDER BY 2,3 ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW) 
FROM TCBLAN LAN 
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE 
(LAN.DTMOV >= :P_PERIODO.INI AND LAN.DTMOV <= :P_PERIODO.FIN)
AND LPAD(PLA.CTACTB,1) IN (3,5) 
AND PLA.ANALITICA = 'S' 
AND PLA.CODCTACTB IN (508,714)
