---DETALHAMENTO DO PRODUTO COM AGRUPAMENTO DE MATERIA PRIMA
------------------------------------------------------------------------

WITH
ITE AS (SELECT * FROM TGFITE ITE),
EST AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
EST1 AS (SELECT EST.CODPROD,SUM(EST.ESTOQUE)ESTOQUE FROM TGFEST EST GROUP BY EST.CODPROD),
APROD AS (SELECT DISTINCT ite.codprod, pro.DESCRPROD,
(CASE
WHEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE)))<=0 THEN (((CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)-SUM(ITE.QTDNEG-ITE.QTDENTREGUE))) ELSE 0 END) A_PRODUZIR
FROM TGFCAB CAB
INNER JOIN tgfpar par ON cab.CODPARC = par.CODPARC 
INNER JOIN tgfite ite ON cab.nunota = ite.nunota
INNER JOIN tgfpro pro ON ite.codprod = pro.codprod
LEFT JOIN EST1 ON ITE.CODPROD = EST1.CODPROD
WHERE 
CAB.CODTIPOPER IN ( 1000,1003,1013,1111,1005)
--And CAB.DTNEG >= TO_DATE('01-01-2021','DD-MM-YYYY') 
--AND CAB.DTNEG <= TO_DATE('04-12-2023','DD-MM-YYYY')
AND CAB.PENDENTE = 'S'
AND CAB.STATUSNOTA = 'L' --SIGNIFICA CONFIRMADA = SIM
GROUP BY
ite.codprod,
pro.DESCRPROD,
(CASE WHEN EST1.ESTOQUE IS NULL THEN 0 ELSE EST1.ESTOQUE END)
ORDER BY 1)
SELECT 
T1.CODMATPRIMA,
PRO3.DESCRPROD,
CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END ESTOQUE,
APROD.A_PRODUZIR*T1.QTDMISTURA A_PRODUZIR,
(CASE WHEN EST.ESTOQUE IS NULL THEN 0 ELSE EST.ESTOQUE END) + (APROD.A_PRODUZIR*T1.QTDMISTURA) SALDO
FROM tgficp t1
INNER JOIN ITE ON T1.CODPROD = ITE.CODPROD
LEFT JOIN EST ON T1.CODMATPRIMA = EST.CODPROD 
INNER JOIN APROD ON T1.CODPROD = APROD.CODPROD
INNER JOIN TGFPRO PRO3 ON T1.CODMATPRIMA = PRO3.CODPROD 
WHERE 
T1.CODPROD = :A_CODPROD1 --263
AND T1.variacao = (SELECT MAX(variacao) FROM tgficp t2 WHERE t1.codprod = t2.codprod)
GROUP BY
T1.CODMATPRIMA,PRO3.DESCRPROD,T1.QTDMISTURA,EST.ESTOQUE,APROD.A_PRODUZIR
ORDER BY 1


