-- VALORES A RECEBER DE VENDA REMESSA FUTURA (ENTREGUE)

SELECT DISTINCT
DTVENC,
DHBAIXA,
NUFIN,
NUMNOTA,
CODTIPOPER,
CODPARC,
CODNAT,
DESCRNAT,
CODBCO,
HISTORICO,

(
(NVL(FIN.VLRDESDOB,0) +
(CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA,0) ELSE 0 END) +
(CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO,0) ELSE 0 END) +
NVL(FIN.DESPCART,0) +
NVL(FIN.VLRVENDOR,0) -
NVL(FIN.VLRDESC,0) -
(CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF,0) ELSE 0 END) -
(CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS,0) ELSE 0 END) -
(CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS,0) ELSE 0 END) -
NVL(FIN.CARTAODESC,0) +
NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP),2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN),0) +
NVL(FIN.VLRMULTANEGOC,0) +
NVL(FIN.VLRJURONEGOC,0) -
NVL(FIN.VLRMULTALIB,0) -
NVL(FIN.VLRJUROLIB,0) +
NVL(FIN.VLRVARCAMBIAL,0)) * NVL(FIN.RECDESP,0)
) AS VLRLIQUIDO



FROM TGFFIN FIN
INNER JOIN TGFNAT NAT ON FIN.CODNAT = NAT.CODNAT
WHERE 
RECDESP = 1
AND DHBAIXA IS NOT NULL
AND PROVISAO = 'N'
AND HISTORICO NOT LIKE '%AD%FORNECEDOR%'