WITH T AS (
SELECT DISTINCT
LIS.NUNOTA,
CAB.CODTIPOPER TOP,
TOP.DESCROPER DESCRTOP,
LIS.CODLST CFOP,
UFS.UF,
CAB.NUMNOTA,
ITE.SEQUENCIA,
CAB.DTFATUR,
--LIS.DTMOV,
LIS.CODEMP,
EMP.RAZAOSOCIAL "EMPRESA",
LIS.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",
CAB.TIPMOV,
ITE.CODPROD,
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD,
ITE.CODTRIB,
PRO.NCM,
PRO.CODVOL,
ITE.QTDNEG,
ITE.VLRUNIT,
ITE.VLRTOT,
(ITE.ALIQICMS/100) AS ALIQICMS,
ITE.BASEICMS,
ITE.VLRICMS,
CAB.VLRFRETE
FROM TGFLIS LIS
INNER JOIN TGFCAB CAB ON LIS.NUNOTA = CAB.NUNOTA
INNER JOIN TGFITE ITE ON LIS.NUNOTA = ITE.NUNOTA AND LIS.SEQUENCIA = ITE.SEQUENCIA
INNER JOIN TSIEMP EMP ON LIS.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON LIS.CODPARC = PAR.CODPARC
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF

UNION ALL

SELECT DISTINCT
LIV.NUNOTA,
CAB.CODTIPOPER TOP,
TOP.DESCROPER DESCRTOP,
LIV.CODCFO CFOP,
UFS.UF,
CAB.NUMNOTA,
ITE.SEQUENCIA,
CAB.DTFATUR,
--LIV.DHMOV DTMOV,
LIV.CODEMP,
EMP.RAZAOSOCIAL "EMPRESA",
LIV.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",
CAB.TIPMOV,
ITE.CODPROD,
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD,
ITE.CODTRIB,
PRO.NCM,
PRO.CODVOL,
ITE.QTDNEG,
ITE.VLRUNIT,
ITE.VLRTOT,
(ITE.ALIQICMS/100) AS ALIQICMS,
ITE.BASEICMS,
ITE.VLRICMS,
CAB.VLRFRETE
FROM TGFLIV LIV
INNER JOIN TGFCAB CAB ON LIV.NUNOTA = CAB.NUNOTA
INNER JOIN TGFITE ITE ON LIV.NUNOTA = ITE.NUNOTA AND LIV.SEQUENCIA = ITE.SEQUENCIA
INNER JOIN TSIEMP EMP ON LIV.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON LIV.CODPARC = PAR.CODPARC
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF

UNION ALL

SELECT DISTINCT
CAB.NUNOTA,
CAB.CODTIPOPER TOP,
TOP.DESCROPER DESCRTOP,
CASE
WHEN (UFS.UF = 'MG' AND CAB.TIPMOV='C') THEN TOP.CODCFO_ENTRADA
WHEN (UFS.UF <> 'MG' AND CAB.TIPMOV='C') THEN TOP.CODCFO_ENTRADA_FORA
WHEN (UFS.UF = 'MG' AND CAB.TIPMOV='V') THEN TOP.CODCFO_SAIDA
WHEN (UFS.UF <> 'MG' AND CAB.TIPMOV='V') THEN TOP.CODCFO_SAIDA_FORA
END AS "CFOP",
UFS.UF,
CAB.NUMNOTA,
ITE.SEQUENCIA,
CAB.DTFATUR,
--CAB.DTMOV DTMOV,
CAB.CODEMP,
EMP.RAZAOSOCIAL "EMPRESA",
CAB.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",
CAB.TIPMOV,
ITE.CODPROD,
PRO.DESCRPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD,
ITE.CODTRIB,
PRO.NCM,
PRO.CODVOL,
ITE.QTDNEG,
ITE.VLRUNIT,
ITE.VLRTOT,
(ITE.ALIQICMS/100) AS ALIQICMS,
ITE.BASEICMS,
ITE.VLRICMS,
CAB.VLRFRETE
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
)

SELECT DISTINCT *
FROM T
WHERE
(DTFATUR >= TRUNC($P{P0}) AND DTFATUR <= TRUNC($P{P1}))
/*AND CODEMP = $P{P3}
AND TIPMOV = $P{P4}
AND (CODPARC = $P{P5} OR $P{P5} IS NULL)
AND (CFOP IN $P{P6} OR $P{P6} IS NULL)
AND (TOP IN ($P!{P7}))*/

ORDER BY
CODPROD,DTFATUR