-- Recebimento Simples
--


SELECT FIN.NUFIN, FIN.NUMNOTA, FIN.CODPARC, PAR.RAZAOSOCIAL, FIN.DTNEG, FIN.DHBAIXA, FIN.VLRDESDOB, FIN.VLRJURO, FIN.VLRMULTA, FIN.VLRDESC, FIN.VLRBAIXA, FIN.HISTORICO, 
FIN.VLRDESDOB * PC.ALIQPIS / 100 AS PIS,
FIN.VLRDESDOB * PC.ALIQCOFINS / 100 AS COFINS
 FROM TGFFIN FIN, TGFPAR PAR, TGFNATPC PC, TGFNATPCEMP E
WHERE FIN.CODPARC = PAR.CODPARC
  AND FIN.CODNAT = PC.CODNAT
  AND PC.NUNATPISCOF = E.NUNATPISCOF
  AND E.CODEMP = FIN.CODEMP
  AND FIN.RECDESP = 1
  AND FIN.ORIGEM = 'E'
  AND FIN.NURENEG IS NULL
  AND FIN.PROVISAO = 'N'
  AND (FIN.DHBAIXA >= :P_PERIODO.INI
  AND FIN.DHBAIXA <= :P_PERIODO.FIN)
  AND FIN.DHBAIXA IS NOT NULL
  AND (FIN.CODEMP = :P_CODEMP OR :P_CODEMP IS NULL)
  AND (FIN.CODPARC = :P_CODPARC OR :P_CODPARC IS NULL)
  AND FIN.CODTIPOPERBAIXA <> 1401
