---FAT BRUTO X RESULTADO

SELECT DISTINCT
TO_CHAR(LAN.DTMOV,'YYYY') ANO,
TO_CHAR(LAN.DTMOV,'MM') MES,
TO_CHAR(LAN.DTMOV,'MM-YYYY') EXERCICIO,
SUM(CASE WHEN LAN.TIPLANC='R' THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D' THEN -1*LAN.VLRLANC END) LUCRO_LIQUIDO,
((SUM(CASE WHEN LAN.TIPLANC='R' THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D' THEN -1*LAN.VLRLANC END))
/
(SUM(CASE WHEN LAN.TIPLANC='R' AND PLA.CODCTACTB IN (508,714) THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D'AND PLA.CODCTACTB IN (508,714) THEN -1*LAN.VLRLANC END)))*100 PART_PERC,

SUM(CASE WHEN LAN.TIPLANC='R' AND PLA.CODCTACTB IN (508,714) THEN 1*LAN.VLRLANC WHEN LAN.TIPLANC='D'AND PLA.CODCTACTB IN (508,714) THEN -1*LAN.VLRLANC END) FAT_BRUTO,
LAN.DTMOV >= ADD_MONTHS(TRUNC(SYSDATE, 'MM'), -1)
AND LAN.DTMOV < TRUNC(SYSDATE, 'MM')

FROM TCBLAN LAN
INNER JOIN TCBPLA PLA ON LAN.CODCTACTB = PLA.CODCTACTB
WHERE 
LPAD(PLA.CTACTB,1) IN (3,5)
AND PLA.ANALITICA = 'S'
AND LAN.CODEMP = 60
GROUP BY
TO_CHAR(LAN.DTMOV,'YYYY'),
TO_CHAR(LAN.DTMOV,'MM'),
TO_CHAR(LAN.DTMOV,'MM-YYYY')
ORDER BY
1,2
