SELECT DISTINCT
CAB.CODEMP AS VALUE,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL AS LABEL
FROM TGFCAB CAB
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
GROUP BY
CAB.CODEMP,
CAB.CODEMP||' - '||EMP.RAZAOSOCIAL
ORDER BY 1


SELECT *
FROM TDDCAM
WHERE NOMECAMPO = 'TIPMOV'




SELECT  DISTINCT
to_CHAR(CAB.DTMOV,'YYYY') ANO,
to_CHAR(CAB.DTMOV,'MM')MES,
CAB.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC,
SUM(CASE WHEN CAB.CODTIPOPER IN (1100,1112,1152) THEN VLRNOTA  ELSE 0 END) AS Saidas,
SUM(CASE WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN VLRNOTA * -1 ELSE 0 END) AS Devolucoes,
SUM(CASE WHEN CAB.CODTIPOPER IN (1105) THEN VLRNOTA ELSE 0  END) AS Servicos,
SUM(CASE WHEN CAB.CODTIPOPER IN (1100,1112,1152) THEN VLRNOTA  ELSE 0 END) +
SUM(CASE WHEN CAB.CODTIPOPER IN (1200,1201,1216,1217) THEN VLRNOTA * -1 ELSE 0 END) +
SUM(CASE WHEN CAB.CODTIPOPER IN (1105) THEN VLRNOTA ELSE 0  END) AS Total
FROM
TGFCAB CAB
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TSIEND ENDI on EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI on EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID on EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE 
(CAB.DTMOV  >=  TO_DATE('01-04-2023','DD-MM-YYYY') AND  CAB.DTMOV <= TO_DATE('30-04-2023','DD-MM-YYYY'))
AND CAB.CODTIPOPER IN (1100,1112,1152,1200,1201,1216,1217,1105)
AND CAB.CODEMP = 60
AND CAB.STATUSNOTA = 'L'
GROUP BY
to_CHAR(CAB.DTMOV,'YYYY'),
to_CHAR(CAB.DTMOV,'MM'),
CAB.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC
ORDER BY 1,2



SELECT
NUNOTA 
FROM
TCIBEM t
WHERE NUNOTA <> 0

SELECT * FROM TGFTOP
WHERE CODTIPOPER IN (301,305,1302)

SELECT * FROM TGFCAB

SELECT CODNAT  FROM TGFFIN WHERE ORIGEM ='E'

SELECT
BEM.NUNOTA,
BEM.NUMNOTA,
TO_CHAR(MOV.REFERENCIA,'MM-YYYY') COMP,
BEM.CODBEM,
BEM.DESCRABREV,
BEM.CODPROD,
PRO.DESCRPROD,
MOV.VLRDEP 
FROM TCIBEM BEM
INNER JOIN TGFPRO PRO ON BEM.CODPROD = PRO.CODPROD
INNER JOIN TCIMOV MOV ON BEM.CODBEM = MOV.CODBEM



SELECT DISTINCT
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 2




SELECT DISTINCT
CAB.NATUREZAOPERDES 
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.DTENTSAI,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM,
ITE.CODPROD,
PRO.DESCRPROD,
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
ITE.VLRTOT
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 3


SELECT CODVEICULO,MARCAMODELO,PLACA, CHASSIS  FROM TGFVEI ORDER BY 1



SELECT * FROM TGFRAT

SELECT
*
FROM TGFVEI

SELECT NUFIN, 
       NUFIN - LAG(NUFIN) OVER (ORDER BY NUFIN) AS A
FROM TGFFIN

SELECT * FROM TGFCAB



SELECT * FROM TGFPRO WHERE DESCRPROD LIKE '%VAGEM%'

SELECT * FROM TGFGRU
SELECT * FROM TCIBEM
SELECT * FROM TCICTE
SELECT * FROM TCIMOV
SELECT * FROM TGFCAB
SELECT * FROM TCICABCTE
SELECT * FROM TCBLAN LAN

AND LAN.NUMLOTE NOT IN (9999)



SELECT 
PRO.CODPROD,
PRO.DESCRPROD,
GRU.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'


SELECT 
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'
GROUP BY 
GRU.DESCRGRUPOPROD,
PRO.USOPROD
ORDER BY 