SELECT
NUNOTA 
FROM
TCIBEM t
WHERE NUNOTA <> 0

SELECT * FROM TGFTOP
WHERE CODTIPOPER IN (301,305,1302)

1404

SELECT CODNAT  FROM TGFFIN WHERE ORIGEM ='E'

SELECT
BEM.NUNOTA,
BEM.NUMNOTA,
TO_CHAR(MOV.REFERENCIA,'MM-YYYY') COMP,
BEM.CODBEM,
BEM.DESCRABREV,
BEM.CODPROD,
PRO.DESCRPROD,
MOV.VLRDEP 
FROM TCIBEM BEM
INNER JOIN TGFPRO PRO ON BEM.CODPROD = PRO.CODPROD
INNER JOIN TCIMOV MOV ON BEM.CODBEM = MOV.CODBEM



SELECT DISTINCT
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 2




SELECT DISTINCT
CAB.NATUREZAOPERDES 
CAB.NUNOTA,
CAB.NUMNOTA,
CAB.DTENTSAI,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
VEI.CODBEM,
ITE.CODPROD,
PRO.DESCRPROD,
PRO.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
ITE.VLRTOT
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
ORDER BY 3


SELECT CODVEICULO,MARCAMODELO,PLACA, CHASSIS  FROM TGFVEI ORDER BY 1



SELECT * FROM TGFRAT

SELECT
*
FROM TGFVEI



SELECT * FROM TGFCAB



SELECT * FROM TGFPRO WHERE DESCRPROD LIKE '%VAGEM%'
SELECT * FROM TGFGRU
SELECT * FROM TCIBEM
SELECT * FROM TCICTE
SELECT * FROM TCIMOV
SELECT * FROM TGFCAB
SELECT * FROM TCICABCTE
SELECT * FROM TCBLAN LAN

AND LAN.NUMLOTE NOT IN (9999)



SELECT 
PRO.CODPROD,
PRO.DESCRPROD,
GRU.CODGRUPOPROD,
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'


SELECT 
GRU.DESCRGRUPOPROD,
PRO.USOPROD
FROM TGFPRO PRO
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD 
WHERE PRO.USOPROD = 'I'
GROUP BY 
GRU.DESCRGRUPOPROD,
PRO.USOPROD
ORDER BY 