SELECT * FROM TGFNFE WHERE NUNOTA IN (5759,5937,5513,6250)
SELECT * FROM TGFRAF
SELECT * FROM TGFFIN

SELECT 
FAT.NUNOTA,       
FAT.NUMNOTA,              
FAT.DTFATUR,       
FAT.VLRNOTA,              
FAT.CODNAT,       
(SELECT NAT.DESCRNAT FROM TGFNAT NAT WHERE NAT.CODNAT = FAT.CODNAT) AS NATUREZA,       
FAT.CODPROJ,       
(SELECT PRJ.IDENTIFICACAO FROM TCSPRJ PRJ WHERE CODPROJ = FAT.CODPROJ) AS PROJETO  
FROM TGFCAB FAT  
WHERE 1=1       
AND FAT.STATUSNOTA NOT IN ('R','P','O')
AND EXTRACT(YEAR FROM FAT.DTFATUR) = '2023'


SELECT STATUSNOTA, STATUSNFE,STATUSNFSE FROM TGFCAB WHERE STATUSNOTA NOT IN ('R','P','O')
SELECT * FROM TDDCAM
SELECT EMP.CODEMP AS VALUE, EMP.NOMEFANTASIA AS LABEL FROM TSIEMP EMP ORDER BY 2


SELECT 
SUM(CAB.VLRNOTA) AS VALOR,
COUNT(CAB.NUNOTA) AS QTD,
SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET,
TO_CHAR(CAB.DTNEG,'MONTH/YYYY') AS MESANO,
TRUNC(CAB.DTNEG,'MM') AS ORDEM
FROM TGFCAB CAB
WHERE
CAB.TIPMOV = 'P'
AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
AND CAB.CODEMP IN :P_EMPRESA
AND (CAB.STATUSNOTA = 'L' OR P_CONFIR = 'N') 
GROUP BY 
TO_CHAR(CAB.DTNEG,'MONTH/YYYY'),
TRUNC(CAB.DTNEG,'MM')



SELECT 
SUM(CAB.VLRNOTA) AS VALOR,
COUNT(CAB.NUNOTA) AS QTD,
SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET
FROM TGFCAB CAB
WHERE
CAB.TIPMOV = 'P'
AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
AND CAB.CODEMP IN :P_EMPRESA
AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
AND (TO_CHAR(CAB.DTNEG,'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)



SELECT
	CAB.NUNOTA,
	CAB.DTNEG,
	CAB.VLRNOTA,
	CASE 
	WHEN :A_TICKET <= CAB.VLRNOTA THEN 1
	WHEN :A_TICKET > CAB.VLRNOTA THEN 2
	WHEN :A_TICKET IS NULL THEN 3 END AS ICONE,
	PAR.CODPARC,
	PAR.NOMEPARC,
	UFS.UF,
	UFS.DESCRICAO,
	CID.NOMECID,
	VEN.CODVEND,
	VEN.APELIDO,
	EMP.CODEMP,
	EMP.NOMEFANTASIA
FROM TGFCAB CAB
	JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC 
	JOIN TSICID CID ON PAR.CODCID = CID.CODCID 
	JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE
	CAB.TIPMOV = 'P'
	AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
	AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
	AND CAB.CODEMP IN :P_EMPRESA
	AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
	AND (TO_CHAR(CAB.DTNEG,'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
	AND (UFS.UF = :A_UF OR :A_UF IS NULL)
	
	
	
	







SELECT

	CAB.NUNOTA,
	CAB.DTNEG,
	CAB.VLRNOTA,
	CASE 
	WHEN :A_TICKET <= CAB.VLRNOTA THEN 1
	WHEN :A_TICKET > CAB.VLRNOTA THEN 2
	WHEN :A_TICKET IS NULL THEN 3 END AS ICONE,
	PAR.CODPARC,
	PAR.NOMEPARC,
	UFS.UF,
	UFS.DESCRICAO,
	CID.NOMECID,
	VEN.CODVEND,
	VEN.APELIDO,
	EMP.CODEMP,
	EMP.NOMEFANTASIA
	SUM(CAB.VLRNOTA) AS VALOR,
	COUNT(CAB.NUNOTA) AS QTD,
	SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET
	FROM TGFCAB CAB
	JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC 
	JOIN TSICID CID ON PAR.CODCID = CID.CODCID 
	JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE
	CAB.TIPMOV = 'P'
	AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
	AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
	AND CAB.CODEMP IN :P_EMPRESA
	AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
	AND (TO_CHAR(CAB.DTNEG,'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
	AND (UFS.UF = :A_UF OR :A_UF IS NULL)




SELECT 
	SUM(CAB.VLRNOTA) AS VALOR,
	COUNT(CAB.NUNOTA) AS QTD,
	SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET
	FROM TGFCAB CAB
	JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC 
	JOIN TSICID CID ON PAR.CODCID = CID.CODCID 
	JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
WHERE
	CAB.TIPMOV = 'P'
	AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
	AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
	AND CAB.CODEMP IN :P_EMPRESA
	AND (CAB.STATUSNOTA = 'L' OR :P_CONFIR = 'N')
	AND (TO_CHAR(CAB.DTNEG,'MONTH/YYYY') = :A_MESANO OR :A_MESANO IS NULL)
GROUP BY
	USF.UF,
	UFS.DESCRICAO,
ORDER BY 3




SELECT NUFIN, 
       NUFIN - LAG(NUFIN) OVER (ORDER BY NUFIN) AS A
FROM TGFFIN



SELECT * FROM TGFFIN WHERE NUFIN = -1120779


SELECT 
SUM(CAB.VLRNOTA) AS VALOR,
COUNT(CAB.NUNOTA) AS QTD,
SUM(CAB.VLRNOTA)/COUNT(CAB.NUNOTA) AS TICKET
FROM TGFCAB CAB
WHERE CAB.TIPMOV = 'P'
AND CAB.DTNEG BETWEEN :P_PERIODO.INI AND :P_PERIODO.FIN
AND (CAB.CODVEND = :P_VENDEDOR OR :P_VENDEDOR IS NULL)
AND CAB.CODEMP IN :P_EMPRESA
AND (CAB.STATUSNOTA = 'L' OR P_CONFIR = 'N')



SELECT DISTINCT
CAB.DTMOV,  
VEI.CODBEM,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA,
SUM(ITE.VLRTOT)
FROM TGFCAB CAB
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD  = GRU.CODGRUPOPROD 
INNER JOIN TGFVEI VEI ON CAB.CODVEICULO = VEI.CODVEICULO
WHERE CAB.CODVEICULO <> 0
AND CAB.CODNAT IN(3050100)
GROUP BY
CAB.DTMOV,
VEI.CODBEM,
CAB.CODVEICULO,
VEI.MARCAMODELO,
VEI.PLACA
ORDER BY 2


