
SELECT * FROM TGFFAI


--- TIULOS RECEBIDOS


SELECT DISTINCT
FIN.CODPARC,
PAR.NOMEPARC,
FIN.CODEMP,
FIN.DTNEG,
FIN.DTVENC,
FIN.DHBAIXA,
FIN.DESDOBRAMENTO,
FIN.VLRDESDOB,
(
(NVL(FIN.VLRDESDOB,0) +
(CASE WHEN FIN.TIPMULTA = '1' THEN NVL(FIN.VLRMULTA,0) ELSE 0 END) +
(CASE WHEN FIN.TIPJURO = '1' THEN NVL(FIN.VLRJURO,0) ELSE 0 END) +
NVL(FIN.DESPCART,0) +
NVL(FIN.VLRVENDOR,0) -
NVL(FIN.VLRDESC,0) -
(CASE WHEN FIN.IRFRETIDO = 'S' THEN NVL(FIN.VLRIRF,0) ELSE 0 END) -
(CASE WHEN FIN.ISSRETIDO = 'S' THEN NVL(FIN.VLRISS,0) ELSE 0 END) -
(CASE WHEN FIN.INSSRETIDO = 'S' THEN NVL(FIN.VLRINSS,0) ELSE 0 END) -
NVL(FIN.CARTAODESC,0) +
NVL((SELECT ROUND(SUM(I.VALOR * I.TIPIMP),2) FROM TGFIMF I WHERE I.NUFIN = FIN.NUFIN),0) +
NVL(FIN.VLRMULTANEGOC,0) +
NVL(FIN.VLRJURONEGOC,0) -
NVL(FIN.VLRMULTALIB,0) -
NVL(FIN.VLRJUROLIB,0) +
NVL(FIN.VLRVARCAMBIAL,0)) * NVL(FIN.RECDESP,0)
) AS VLRLIQUIDO,


FIN.VLRBAIXA,
FIN.CODTIPTIT,
TIP.DESCRTIPTIT,
FIN.CODCTABCOINT,
FIN.NUFIN,
FIN.NUMNOTA,
FIN.NOSSONUM,
CTA.CODBCO,
CTA.DESCRICAO,
CTA.CODAGE,
FIN.RECDESP
FROM TGFFIN FIN
INNER JOIN TSICTA CTA ON FIN.CODCTABCOINT = CTA.CODCTABCOINT
INNER JOIN TGFPAR PAR ON FIN.CODPARC = PAR.CODPARC
INNER JOIN TGFTIT TIP ON FIN.CODTIPTIT = TIP.CODTIPTIT
WHERE
VLRBAIXA <> 0
AND (FIN.DHBAIXA >= '01/03/2023' AND FIN.DHBAIXA <= '31/03/2023')
AND PAR.CLIENTE = 'S'
AND FIN.RECDESP = 1
ORDER BY
PAR.NOMEPARC,
FIN.DTVENC,
FIN.CODPARC,
FIN.NUMNOTA