SELECT DISTINCT

CAB.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL "PARCEIRO",

SUM(CASE 
WHEN (CAB.CODTIPOPER IN (1111,1116) AND CAB.TIPMOV = 'V') THEN (ITE.QTDNEG * -1)
WHEN (CAB.CODTIPOPER IN (1112,1152,1153,1213) AND CAB.TIPMOV = 'V') THEN (ITE.QTDNEG)
WHEN (CAB.TIPMOV = 'D') THEN (ITE.QTDNEG * -1)  
ELSE 0  END) C,

AVG(ITE.VLRUNIT) VLRUNIT_AVG,

SUM(CASE
WHEN (CAB.CODTIPOPER IN (1111,1116) AND CAB.TIPMOV = 'V') THEN (ITE.VLRTOT * -1)
WHEN (CAB.CODTIPOPER IN (1112,1152,1153,1213) AND CAB.TIPMOV = 'V') THEN (ITE.VLRTOT)
WHEN (CAB.TIPMOV = 'D') THEN (ITE.VLRTOT * -1)
END) AS VLRTOT


FROM
TGFCAB CAB

INNER JOIN TGFTPV TPV ON CAB.CODTIPVENDA = TPV.CODTIPVENDA
INNER JOIN TGFITE ITE ON CAB.NUNOTA = ITE.NUNOTA
INNER JOIN TSIEMP EMP ON CAB.CODEMP = EMP.CODEMP
INNER JOIN TGFPAR PAR ON CAB.CODPARC = PAR.CODPARC
INNER JOIN TGFPRO PRO ON ITE.CODPROD = PRO.CODPROD
INNER JOIN TGFGRU GRU ON PRO.CODGRUPOPROD = GRU.CODGRUPOPROD
INNER JOIN TSICID CID ON PAR.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN TGFTOP TOP ON CAB.CODTIPOPER = TOP.CODTIPOPER


WHERE
CAB.CODTIPOPER IN (1111,1116,1152,1153,1213,1112)
AND CAB.CODPARC = 9179

GROUP BY
CAB.CODPARC,
PAR.CGC_CPF,
PAR.RAZAOSOCIAL

ORDER BY
PARCEIRO
