-- DADOS DA ORDEM DE PRODUÇÃO
SELECT
 (SELECT COUNT (APO.NUAPO)
  	FROM TPRAPO APO
          INNER JOIN TPRIATV ATV ON APO.IDIATV = ATV.IDIATV
			WHERE ATV.IDIPROC = 485) AS QTDAPO
,    (SELECT CP.NOME
	 FROM TPRWXIP IP, TPRWCP CP, TPRIPROC OP
           WHERE IP.IDIPROC =  OP.IDIPROC
           AND IP.CODWCP = CP.CODWCP
           AND OP.IDIPROC = 485) AS CT
, DHINC INCLUSAO
, DHINST INICIO
, DHTERMINO TERMINO
, OP.IDIPROC
, PRO.CODVOL
, ROUND(IPA.QTDPRODUZIR)
, ROUND(ap.qtdapontada)
, USU.NOMEUSU SOLICITANTE
, PRO.DESCRPROD PRODUTOPA
, PRO.COMPLDESC COMPLEMENTO
, PRO.CODPROD PRODUTO_ID
, CASE WHEN STATUSPROC = 'A' THEN 'Inicializada'
       WHEN STATUSPROC = 'C' THEN 'Cancelada'
       WHEN STATUSPROC = 'F' THEN 'Finalizada'
       WHEN STATUSPROC = 'R' THEN 'Não Iniciada'
       WHEN STATUSPROC = 'S' THEN 'Suspensa'
       ELSE '' END AS STATUS
, DHTERMINO
, round(DHTERMINO - DHINST) || ' Dias ' ||
round((((DHTERMINO - DHINST) * 1440) -(round((DHTERMINO - DHINST))*1440))/60) || ' Horas ' ||
round(((DHTERMINO - DHINST) * 1440) -(round((DHTERMINO - DHINST))*1440))  || ' Minutos'
PERIODO
, OP.NROLOTE LOTE
, INITCAP(PRC.DESCRABREV) DESCRPROC
, NVL(OP.NUNOTA,0) AS PEDIDO
,(SELECT SUBSTR(LOGODANFE, INSTR(LOGODANFE, '/', -1) + 1, LENGTH(LOGODANFE)) FROM TGFEMP WHERE CODEMP = OP.CODPLP) AS LOGO_EMP
FROM TPRIPROC OP, TSIUSU USU, TGFPRO PRO, TPRIPA IPA left join (
  SELECT SUM(QTDAPONTADA) AS QTDAPONTADA, CODPRODPA
  FROM TPRAPA
  WHERE NUAPO IN(SELECT (APO.NUAPO)
                    FROM TPRAPO APO
                    INNER JOIN TPRIATV ATV ON APO.IDIATV = ATV.IDIATV
                    WHERE ATV.IDIPROC = 485
                )
GROUP BY CODPRODPA
) AP ON IPA.CODPRODPA = AP.CODPRODPA, TPRPRC PRC
WHERE OP.IDIPROC = IPA.IDIPROC
AND USU.CODUSU = OP.CODUSUINC
AND PRO.CODPROD = IPA.CODPRODPA
AND PRC.IDPROC = OP.IDPROC
AND OP.IDIPROC = 485




-----------------APONTAMENTOS
SELECT
 (SELECT COUNT (APO.NUAPO)
  	FROM TPRAPO APO
          INNER JOIN TPRIATV ATV ON APO.IDIATV = ATV.IDIATV
          WHERE ATV.IDIPROC= 485) AS QTDAPO

,    (SELECT CP.NOME
	 FROM TPRWXIP IP, TPRWCP CP, TPRIPROC OP
           WHERE IP.IDIPROC =  OP.IDIPROC
           AND IP.CODWCP = CP.CODWCP
           AND OP.IDIPROC = 485) AS CT

--, (SELECT DISTINCT DESCRTURMA FROM AD_CADTURMA WHERE NUTURMA = (SELECT DISTINCT (AP.AD_NUTURMA)
--                    FROM TPRAPO AP
--                    INNER JOIN TPRIATV ATV ON AP.IDIATV = ATV.IDIATV
--                    WHERE ATV.IDIPROC = 28
--                     AND AP.AD_NUTURMA >= 0)) AS TURMA
, DHINC INCLUSAO
, DHINST INICIO
, DHTERMINO TERMINO
, OP.IDIPROC
, PRO.CODVOL
, ROUND(IPA.QTDPRODUZIR)
, ROUND(ap.qtdapontada)
, USU.NOMEUSU SOLICITANTE
, PRO.DESCRPROD PRODUTOPA
, PRO.COMPLDESC COMPLEMENTO
, PRO.CODPROD PRODUTO_ID
, CASE WHEN STATUSPROC = 'A' THEN 'Inicializada'
       WHEN STATUSPROC = 'C' THEN 'Cancelada'
       WHEN STATUSPROC = 'F' THEN 'Finalizada'
       WHEN STATUSPROC = 'R' THEN 'Não Iniciada'
       WHEN STATUSPROC = 'S' THEN 'Suspensa'
       ELSE '' END AS STATUS
, DHTERMINO
, round(DHTERMINO - DHINST) || ' Dias ' ||
round((((DHTERMINO - DHINST) * 1440) -(round((DHTERMINO - DHINST))*1440))/60) || ' Horas ' ||
round(((DHTERMINO - DHINST) * 1440) -(round((DHTERMINO - DHINST))*1440))  || ' Minutos'
PERIODO
, OP.NROLOTE LOTE
, INITCAP(PRC.DESCRABREV) DESCRPROC
, NVL(OP.NUNOTA,0) AS PEDIDO
,(SELECT SUBSTR(LOGODANFE, INSTR(LOGODANFE, '/', -1) + 1, LENGTH(LOGODANFE)) FROM TGFEMP WHERE CODEMP = OP.CODPLP) AS LOGO_EMP
FROM TPRIPROC OP, TSIUSU USU, TGFPRO PRO, TPRIPA IPA left join (
  SELECT SUM(QTDAPONTADA) AS QTDAPONTADA, CODPRODPA
  FROM TPRAPA
  WHERE NUAPO IN(SELECT (APO.NUAPO)
                    FROM TPRAPO APO
                    INNER JOIN TPRIATV ATV ON APO.IDIATV = ATV.IDIATV
                    WHERE ATV.IDIPROC=485
                )
GROUP BY CODPRODPA
) AP ON IPA.CODPRODPA = AP.CODPRODPA, TPRPRC PRC
WHERE OP.IDIPROC = IPA.IDIPROC
AND USU.CODUSU = OP.CODUSUINC
AND PRO.CODPROD = IPA.CODPRODPA
AND PRC.IDPROC = OP.IDPROC
AND OP.IDIPROC = 485



------ETAPAS DE PRODUÇÃO
