
SELECT DISTINCT
ORD.CODEMP,
EMP.RAZAOSOCIAL,
ENDI.NOMEEND,
EMP.NUMEND,
EMP.COMPLEMENTO,
BAI.NOMEBAI,
CID.NOMECID,
UFS.UF,
EMP.CEP,
EMP.CGC,
EMP.INSCESTAD,
EMP.INSCMUN,
EMP.TELEFONE,
ORD.ORDEMCARGA,
PAR.RAZAOSOCIAL,
ORD.CODVEICULO,
VEI.PLACA,
VEI.CODCID,
CID1.NOMECID,
PAR1.RAZAOSOCIAL,
CID2.NOMECID,
UFS1.UF,
ORD.ROTEIRO,
CAB.OBSERVACAO,
CAB.AD_NUTICKET
FROM TGFORD ORD
INNER JOIN TSIEMP EMP ON ORD.CODEMP = EMP.CODEMP
INNER JOIN TSIEND ENDI on EMP.CODEND = ENDI.CODEND
INNER JOIN TSIBAI BAI on EMP.CODBAI = BAI.CODBAI
INNER JOIN TSICID CID on EMP.CODCID = CID.CODCID
INNER JOIN TSIUFS UFS ON CID.UF = UFS.CODUF
INNER JOIN TGFCAB CAB ON ORD.ORDEMCARGA = CAB.ORDEMCARGA
INNER JOIN TGFPAR PAR ON ORD.CODPARCTRANSP = PAR.CODPARC
INNER JOIN TGFVEI VEI ON ORD.CODVEICULO = VEI.CODVEICULO 
INNER JOIN TSICID CID1 on VEI.CODCID = CID1.CODCID
INNER JOIN TGFPAR PAR1 ON CAB.CODPARC = PAR1.CODPARC
INNER JOIN TSICID CID2 ON PAR1.CODCID = CID2.CODCID
INNER JOIN TSIUFS UFS1 ON CID2.UF = UFS1.CODUF
WHERE
PAR.TRANSPORTADORA = 'S'


UPDATE TGFITE
SELECT * FROM TSICID
SELECT * FROM TSIUFS
SELECT * FROM TGFCAB
SELECT * FROM TGFVEI
SELECT * FROM TGFORD
SELECT * FROM TGFPAR WHERE TRANSPORTADORA = 'S'
SELECT ORDEMCARGA FROM TGFCAB WHERE ORDEMCARGA IS NOT NULL
SELEC




SELECT OPC.* 
FROM TDDCAM CAM 
JOIN TDDOPC OPC ON OPC.NUCAMPO = CAM.NUCAMPO
WHERE CAM.NOMETAB='TGFORD' AND CAM.NOMECAMPO='CODTIPPARC'
ORDER BY OPC.ORDEM